### ISSUE TITLE
ofSetBackgroundAuto(false) breaks when resizing the window

### ISSUE THREAD

**Issue by hamoid** [openframeworks/openFrameworks#5625] opened 2017-05-21 16:03 UTC
```cpp
void ofApp::setup() {
    ofSetBackgroundAuto(false);
}
void ofApp::keyPressed(int key) {
    cout << key << endl;
}
```

Before resizing, the keys are printed. 
After resizing it stops printing the keys. 

Once I saw the couts suddenly show up in the console after a minute or so. Sometimes the program refuses to close when I press the OS key combination to close a program, but again, if I wait for a minute or two, the window eventually closes.

ArchLinux 64bit, Mesa 17.1.0, integrated graphics, GL Core Profile 4.5, GLES1: 1.1, GLES[23]: 3.1. OF: git master from 12.2016 with some recent fixes backported :)

Does this work on other OSes or versions?

**Comment by bakercp** [comment] 2017-05-22 02:55
This sounds suspiciously like a GLFW bug ... have you tried installing the latest release of GLFW from source?  A lot of other strange behaviors on linux have been fixed with updated GLFW.

**Comment by hamoid** [comment] 2017-05-22 07:18
Thanks, I'll give it a try and report back.

**Comment by arturoc** [comment] 2017-05-22 07:23
abe if you are on archlinux you surely already have the very last version of glfw

**Comment by hamoid** [comment] 2017-05-22 07:23
What do you mean with "release from source"? :) I see I run their latest stable release, 3.2.1. Do you mean I should compile their master branch?

**Comment by bakercp** [comment] 2017-05-22 15:00
I can't reproduce on macOS, here is my code.

```c++
#include "ofApp.h"

void ofApp::setup()
{
    ofSetBackgroundAuto(false);
}

void ofApp::draw()
{
}


void ofApp::keyPressed(int key)
{
    std::cout << key << std::endl;
}
```

```c++
#pragma once

#include "ofMain.h"

class ofApp : public ofBaseApp{
public:
    void setup();
    void draw();
    void keyPressed(int key);
};

```

**Comment by arturoc** [comment] 2017-05-22 15:04
yes this is probably a platform specific issue i remember like it's come up before. Abe if you are looking into doing the tipical trails effect you are better off using an fbo instead where you can also have float precision if you initialize if with GL_RGBA32. take a look at the fboTrailsExample

**Comment by hamoid** [comment] 2017-05-22 15:23
I wasn't doing trails or even animation, but porting this https://twitter.com/hamoid/status/865931219132960769

I use the i3 tiling window manager, which does automatic layout of windows. After starting the app I must "float" the window (it detaches from the automatic grid and resizes to the requested ofApp width and height). Then I press a key or click the mouse to start the program. But resizing the window breaks interaction, so I could not start the program. 

I did use an fbo and it worked fine :)

**Comment by bakercp** [comment] 2017-05-22 17:52
A few possibly related issues related to TWMs w/ GLFW and i3 in particular: 

https://github.com/glfw/glfw/issues/293
https://github.com/glfw/glfw/issues/731
https://github.com/glfw/glfw/issues/995

**Comment by hamoid** [comment] 2017-05-22 19:36
_Note: please ignore the following until I make 3DPrimitivesExample work again_

Thanks for finding these @bakercp .

I did some investigation and now I'm even more confused. There seem to be two things affecting my program. The first is ofSetBackgroundAuto(false).

The second looks like this:

```cpp
void ofApp::draw() {
    if(render) {
        render = false;
        for(int i=0; i<10000; i++) {
            ofDrawLine(0, 0, 0, 800, 800, 800);        
        }
        ofDrawCircle(0, 0, 200);
    }
}
void ofApp::mousePressed(int x, int y, int button) {
    render = true;
}
```

Depending on the number of lines drawn when I click, I see nothing, incomplete lines, or the line and the circle. With 3000 it looks right. With 7000 I see part of the line and the circle, sometimes. With 10000 I see nothing.

Drawing 10000 lines is not such a big deal, or? I was wondering if Mesa / Intel drivers are broken again, so I tried running 3DPrimitivesExample and indeed, no triangles are visible, only the normals. I will ask about that in a different issue.

**Comment by bakercp** [comment] 2017-05-22 19:42
Got pictures or animation?  Could it be an anti-aliasing issue (if you draw them at random positions does it change things)?  You do appear to be drawing a lot of lines on top of each other in 3d, which may lead to some rendering artifacts.

**Comment by hamoid** [comment] 2017-05-22 20:04
Not an anti-aliasing issue. I changed the loop to this:

```cpp
for(int i=0; i<1000; i++) {
    ofDrawLine(0, 0, 0, ofRandom(800), ofRandom(800), ofRandom(800));        
}
```

With 1000, every time I click I see one frame with a "sun and rays". If I increase it, there are artifacts: sometimes I see a horizontal band showing part of the "sun and rays", most of the time, nothing.

https://vimeo.com/218522084/214718b96a

**Comment by bakercp** [comment] 2017-05-22 20:25
It seems to be a combination of lack of vertical sync (the horzintal "tearing") and the fact that you are manually resetting your background to black every time (with `ofBackground(0)`).  Can you add `    ofSetVerticalSync(true)` to your setup, and get rid of the `ofBackground(0)` line?

**Comment by hamoid** [comment] 2017-05-22 21:08
* ofSetVerticalSync(true) and ofBackground(0) seem unrelated.
* Running in full screen fixes the issue.
* The execution time of the loop seems unrelated (I can't match execution time to the visuals produced).

```cpp
    if(ofGetFrameNum() % 30 == 0) {
        auto t = ofGetElapsedTimeMillis();
        for(int i=0; i<3000; i++) {
            ofDrawLine(0, 0, 0, ofRandom(800), ofRandom(800), ofRandom(800));        
        }
        ofDrawCircle(0, 0, 200);
        cout << ofGetElapsedTimeMillis() - t << " ms" << endl;
    }
```

I believe it must be some quirk in my system: ArchLinux, recent drivers, integrated graphics. Since this probably does not affect others, I would just close the issue and I work around it.

Nice to see GitHub being cleaned up! :)

**Comment by ofZach** [comment] 2017-05-22 21:19
(for a long time I've thought it might make sense to use, where we can, an internal FBO for non background auto -- it seems like almost every graphics card has FBO support...  I've always felt the way we do non background auto clearing is kind of wonky on certain graphics cards, etc....)

**Comment by bakercp** [comment] 2017-05-22 21:40
@ofZach PR sounds interesting !  @hamoid I'll close this for now, since I'm on a mission to take a little bite out of the 700+ issues :) Of course if there's a clear set of quirks that we can document / fix, then let's reopen and fix it.

**Closed by bakercp** 2017-05-22 21:40 UTC
Labels: core, linux, upstream
