### ISSUE TITLE
can not run the ofxKinect addon

### ISSUE THREAD

**Issue by jing1234** [openframeworks/openFrameworks#5481] opened 2017-03-13 19:14 UTC
Hi,
I meet 2 compiler errors. It can not open “unistd.h” and “freenect_internal.h”. But the 2 files are in the ofxKinect file. Why ?
e:\ma\of_v0.9.8_vs_release\of_v0.9.8_vs_release\addons\ofxkinect\libs\libfreenect\platform\windows\libusb10emu\libusb-1.0\libusb.h(37): fatal error C1083: can not open: “unistd.h”: No such file or directory (..\..\ofxKinect\libs\libfreenect\platform\windows\libusb10emu\libusb-1.0\libusbemu.cpp)

..\..\ofxKinect\libs\libfreenect\src\registration.c(28): fatal error C1083: can not open : “freenect_internal.h”: No such file or directory

![filetree](https://cloud.githubusercontent.com/assets/18555526/23871184/a2d5af40-0829-11e7-934f-cd9f107f13b3.png)

Thanks
jing

**Comment by bakercp** [comment] 2017-05-21 01:30
Does this work with the openFrameworks master branch?

**Comment by bakercp** [comment] 2017-05-22 16:42
Closing this as a duplicate of #5503 by the same user.

**Closed by bakercp** 2017-05-22 16:42 UTC
Labels: addon, visual studio, windows
