### ISSUE TITLE
openFrameworks Truck Factor

### ISSUE THREAD

**Issue by gavelino** [openframeworks/openFrameworks#4198] opened 2015-08-06 11:44 UTC
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **openFrameworks** and obtained a value of **2**.

The developers responsible for this TF are:

arturo - author of 68% of the files
ofTheo - author of 42% of the files

To validate our results, we would like to ask **openFrameworks** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **openFrameworks**?

(b) Do you agree that **openFrameworks** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **openFrameworks** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by bakercp** [comment] 2015-08-06 12:15
Hi, this discussion would better be carried out on our forum.

- A few of your questions could be answered by looking at 
https://github.com/openframeworks/openFrameworks/graphs/contributors etc.

- why does your percentage add up to 110%

- the link to your preprint int accessible on mobile.

**Comment by bilderbuchi** [comment] 2015-08-06 12:30
Yes, the forum would be a better place to discuss this. Also, we [recently](http://dev.openframeworks.cc/htdig.cgi/of-dev-openframeworks.cc/2015-July/033971.html) had a bit of discussion on our mailing list, in retrospect probably triggered by your paper.

A couple of remarks:
* I have never heard anybody yet calling this *truck* factor, only *bus factor*. :-P
* I find it questionable to equate file "ownership" with "concentration of information" as the relevant metric for establishing bus factor.
* This totally disregards outside mitigation features like having shared knowledge, a wiki, a set of developer teams which share information, mailing lists, forums, regular meetings/conferences, etc. Judging purely from code history gives an imcomplete picture, at best.
* Personally, I'd estimate the BF of openFrameworks to be ~4, that is the @openframeworks/core developer team.
* Regarding question a): That's an imprecisely worded question: both are main developers, but they are not _all_ the main developers, see above
* Regarding question b): No, see above
* Regarding question c): Yes, see above. Imo this calculation is too imprecise to be useful (but I realize that it's probably as much as you can do in an automated fashion)
* I like how the DOA calculation in the paper is full of magic numbers...

**Comment by bilderbuchi** [comment] 2015-08-06 12:34
Also, closing this as it's not a bug, and this is not the venue to discuss this. 
Furthermore, I see from your public activity that you right now probably flooded all the investigated projects with your findings as a cheap way to do a user survey (I guess) - it would be great if you would actually take your time and show your appreciation of the individual projects by bringing this to the proper venue for discussion, information that many projects have easily available e.g. in a CONTRIBUTING document.

**Closed by bilderbuchi** 2015-08-06 12:34 UTC

**Comment by bakercp** [comment] 2015-08-06 13:42
It does feel like a lot of people like @arturoc are working at 110% capacity though -- so maybe the algorithm accounts for that ;)

**Comment by gavelino** [comment] 2015-08-06 17:13
Hi,

>why does your percentage add up to 110%

The percentage represents the files of the system that developers are considered author, but our approach allows more than one author by file. So the sum of developer's authorship can be higher than 100%.

**Comment by ofTheo** [comment] 2015-08-06 18:16
wow - this is super grim terminology. 
could also be called falling piano factor, ebola factor? :) 

Seriously though I think the % is not accurate at least for me ( ofTheo ). 
A lot of that might come from when we moved OF from SVN to Git - I think I was the one that set it up. 

If instead your code looked at commits made to a file or a new file added after the creation date and initial few repo commits, it might be a bit more accurate. 

I would also be curious about how time is applied with this approach. 
As a projects Truck factor probably changes over time. 
I would say OF has changed a lot in the last couple of years so I would be curious what your results would look like for last 1 year, last 2 years etc. 

Anyway in the meantime, Arturo, keep an eye out for trucks! 

----------------------------------------------
Theo Watson
http://theowatson.com 
http://openframeworks.cc
----------------------------------------------

**Comment by gavelino** [comment] 2015-08-12 17:20
Thank you for the comments. We really appreciate the feedback.

Our research is under development and the answers we are receiving for this survey will help to better interpret the results and improve our approach.

@ofTheo we pretend to study as a projects Truck factor changes over time in future.
