### ISSUE TITLE
gitignore for project generator

### ISSUE THREAD

**Issue by fooness** [openframeworks/openFrameworks#5334] opened 2016-11-04 10:08 UTC
Dear openFrameworkers,

I thought there’d already be a .gitignore file project generator on OSX uses when creating new projects. https://github.com/openframeworks/openFrameworks/issues/2791

Wasn’t that added to openFrameworks (osx-v0.9.7) yet? Kindest regards!

**Comment by d-egan** [comment] 2017-12-20 15:11
Sounds like a duplicate of #5792 ?
Closed with #5824

**Comment by bakercp** [comment] 2017-12-20 15:15
It sure looks like it.  @fooness if you don't agree, please reopen with additional information.

**Closed by bakercp** 2017-12-20 15:15 UTC
