### ISSUE TITLE
CMake / Hunter / Cross-Compilation

### ISSUE THREAD

**Issue by lucmichalski** [openframeworks/openFrameworks#5143] opened 2016-06-30 14:29 UTC
Hi guys,

hope you are doing all well !

I was wondering if there is any projects related to openframeworks allowing to compile ofx librairies and app with CMake.

The bigger goal would be to use:
- https://github.com/ruslo/hunter
- https://github.com/ruslo/polly
- https://github.com/hunter-packages

It would allow to make easier the cross-compilation of projects (Linux, Mac, Windows, iOS, Android, Raspberry Pi).

Cheers,
Luc Michalski

**Comment by andyli** [comment] 2016-07-29 23:55
duplicate of #4193

**Comment by damian0815** [comment] 2016-12-08 21:36
Surprised no-one has mentioned ofnode yet. https://github.com/ofnode/of

**Comment by bakercp** [comment] 2017-05-22 21:00
Closing this as a duplicate.

**Closed by bakercp** 2017-05-22 21:00 UTC
