### ISSUE TITLE
 AVFoundation player isFrameNew()

### ISSUE THREAD

**Issue by ImanolGo** [openframeworks/openFrameworks#5509] opened 2017-03-29 08:23 UTC
Hi OF community,

I'm having an issue with the AVFoundation player and I would like to discuss it with you. 

First of all, I'm working on a  MacBook Pro Retina 15 inch with dedicated graphics card and MacOS 10.12 Sierra

So, let's get started:

First of all the method is frame new is not working properly. If I do this:

```
    if(videoPlayer.isFrameNew())
    {
        //Do something
    }

```
I get more calls than frames are in the video.

That I fixed it like this:
        

```
         if(videoPlayer.isFrameNew())
            {
                int frame = videoPlayer.getCurrentFrame();
                if(m_frameNumber != frame)
                {
                      m_frameNumber = frame;
                      //Do something
                }
            }
```
    
That didn't happen with the QTKit base player.

**Comment by bakercp** [comment] 2017-05-20 21:50
Duplicate of #5420 closing.

**Closed by bakercp** 2017-05-20 21:50 UTC
Labels: section-video
