### ISSUE TITLE
removing using namespace std from core

### ISSUE THREAD

**Issue by tpltnt** [openframeworks/openFrameworks#4034] opened 2015-07-01 09:06 UTC
This ticket spawned of #4012 & #2851. `using namespace std` shall be moved from `ofConstants.h` into `ofMain.h` to ease the transition for beginners. There could also group headers be added per folder so including different modules. `ofUtils.h` would include everything in the utils folder.

**Comment by tpltnt** [comment] 2015-07-01 09:06
ping @arturoc @tgfrerer

**Comment by bilderbuchi** [comment] 2015-07-01 09:12
Closed as duplicate of #2581

**Closed by bilderbuchi** 2015-07-01 09:12 UTC
Labels: core, development-strategy, feature, prelim-analysis, section-internals
