### ISSUE TITLE
Raspberry Pi compile bugs on master

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#3529] opened 2015-01-08 02:23 UTC
A few compile issues on master:

```
In file included from ../../../libs/openFrameworks/utils/ofLog.h:6:0,
                 from ../../../libs/openFrameworks/types/ofRectangle.h:6,
                 from ../../../libs/openFrameworks/graphics/ofGraphics.h:7,
                 from ../../../libs/openFrameworks/events/ofEvents.cpp:198:
../../../libs/openFrameworks/types/ofTypes.h:13:18: error: ‘shared_ptr’ is already declared in this scope
../../../libs/openFrameworks/types/ofTypes.h:14:18: error: ‘weak_ptr’ is already declared in this scope
../../../libs/openFrameworks/types/ofTypes.h:15:18: error: ‘enable_shared_from_this’ is already declared in this scope
```

```
../../../libs/openFrameworks/gl/ofGLUtils.cpp: In function ‘int ofGetBytesPerChannelFromGLType(int)’:
```
```
../../../libs/openFrameworks/gl/ofGLUtils.cpp:651:8: error: ‘GL_HALF_FLOAT’ was not declared in this scope
```

**Comment by bilderbuchi** [comment] 2015-01-08 19:51
first one: probably something going wrong with the [macro](https://github.com/openframeworks/openFrameworks/blob/d95533d94c45f4bae1de5956d2539b201047bad0/libs/openFrameworks/types/ofTypes.h#L12) for C++11 detection?

**Comment by bakercp** [comment] 2015-01-08 20:00
Indeed, the defines around the redefinition have changed since 0.8.4 and the rpi makefiles now compile w/ c++11 ... I haven't done any investigation, just marking this as an issue to figure out at some point before 0.9.0.

For whatever reason, even though c++11 is being used, the preprocessor still lets these tr1 definitions through ... so one of those defines -- perhaps TARGET_LINUX is not being defined or something?

**Comment by jvcleave** [comment] 2015-01-11 06:03
There is quite a bit more broken further down the chain because of the pure virtual functions e.g. `virtual void draw()` that `ofAppEGLWindow` is required to have as it extends `ofAppBaseWindow`

https://github.com/openframeworks/openFrameworks/commit/1839c0bd9b21b7a578e41b0282447afd873f7ef9

**Comment by bilderbuchi** [comment] 2015-01-11 08:57
Pinging @arturoc, then.

**Comment by jvcleave** [comment] 2015-01-11 20:31
going to try and update `ofAppEGLWindow` for the next few hours referencing some of the other ofApp*Window - will be in IRC

**Comment by jvcleave** [comment] 2015-01-11 22:36
ok - I got emptyExample to comple/run with this but it's not drawing anything but the gray background

https://github.com/jvcleave/openFrameworks/commit/23fef1a6cdae87520eca9e0afde2595618eb3a19

**Comment by arturoc** [comment] 2015-01-12 11:34
just left a comment, everything else seems correct but let me know if it still doesn't work and i'll try to take a look

**Comment by jvcleave** [comment] 2015-01-12 18:55
@arturoc 

made the changes -

update
draw/display

are being called (and is now exiting properly)

not seeing any drawing yet with graphicsExample - just the gray background still

https://github.com/jvcleave/openFrameworks/commit/857d50dfca09f37072d02ec1c5cce9ee1c76be20

**Comment by jvcleave** [comment] 2015-02-13 07:16
@arturoc just pinging to see if you have any other insights? I should have some more time next week to fix (and hopefully an RPI2 as well)

**Comment by arturoc** [comment] 2015-02-13 13:50
haven't had time to check it but it seems correct to me, i'll give it a try this weekend

**Comment by orsjb** [comment] 2015-02-14 05:26
Hi, I've got the same problem. Just tried compiling now. In ofTypes.h, "shared_ptr", "weak_ptr" and "enable_shared_from_this" are all already declared in scope. Fresh checkout of openFrameworks from git yesterday. Raspbian Wheezy 2014-01-07.

**Closed** 2015-02-16 21:33 UTC
Labels: bug, core, critical, linuxarm

**Comment by orsjb** [comment] 2015-02-17 01:18
On 662830f I'm still getting the compile error. Clean install of Raspbian Wheezy 2014-01-07.
Is there a test to ensure I have correct dependencies?

Also note I don't have gst-launch-1.0 as per this thread: http://forum.openframeworks.cc/t/videoplayerexample-on-raspberrypi/18525/3.

**Comment by jvcleave** [comment] 2015-02-17 03:40
@arturoc thanks for the updates!

Is there a new way to specify the `ofGLProgrammableRenderer`?

The way I was using (and still in a lot of the OF tutorial apps)

`ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);`

gets me this

```
‘ofGLProgrammableRenderer::TYPE’ from ‘const string {aka const std::basic_string<char>}’ to ‘std::shared_ptr<ofBaseRenderer>’
  ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);
```

using

`ofSetCurrentRenderer(ofPtr<ofBaseRenderer>(new ofGLProgrammableRenderer()));`

causes

```
 error: no matching function for call to ‘ofGLProgrammableRenderer::ofGLProgrammableRenderer()’
  ofSetCurrentRenderer(ofPtr<ofBaseRenderer>(new ofGLProgrammableRenderer()));
                                                                          ^
src/main.cpp:10:74: note: candidates are:
In file included from ../../../libs/openFrameworks/ofMain.h:50:0,
                 from src/main.cpp:1:
../../../libs/openFrameworks/gl/ofGLProgrammableRenderer.h:22:2: note: ofGLProgrammableRenderer::ofGLProgrammableRenderer(const ofAppBaseWindow*)
  ofGLProgrammableRenderer(const ofAppBaseWindow * window);

```

Apparently  main.cpp needs to pass an ofAppBaseWindow?

**Comment by tgfrerer** [comment] 2015-02-17 09:40
Hey @jvcleave, to select the programmable renderer, instead of the old method, try setting the GLES version to 2 - as in:

    # main.cpp

    ofGLESWindowSettings settings;
    settings.setGLESVersion(2);

    ofCreateWindow(settings);

**Comment by arturoc** [comment] 2015-02-17 11:12
yes that's it, i actually need to turn the current ofAppEGLWindow::Settings class to extend ofGLESWindowSettings so you can pass all those parameters too when setting up the window.

**Comment by jvcleave** [comment] 2015-02-17 16:52
That did it :) (wow - `ofSetupOpenGL` is gone? RIP)

For anyone else stumbling across this  - this did it for me

```
#include "ofMain.h"
#include "testApp.h"

int main()
{
	ofGLESWindowSettings settings;
	settings.width = 1280;
	settings.height = 720;
	settings.setGLESVersion(2);
	ofCreateWindow(settings);
	
	ofRunApp( new testApp());
}
```

**Comment by trentbrooks** [comment] 2015-02-17 23:38
I have same compile issues as @orsjb on rpi2. Steps to reproduce...
- cloned a fresh master today (last commit https://github.com/openframeworks/openFrameworks/commit/1b4eab4fad3c9016c8b5a1d7fbe78b36b18584da)
- install dependencies, codecs scripts (linux/debian)
- enter following 2 commands (https://github.com/openframeworks/openFrameworks/issues/3620):
export MAKEFLAGS='-j4 -s PLATFORM_VARIANT=rpi2' 
make Release -C /home/pi/openFrameworks/libs/openFrameworksCompiled/project

Am I missing something?

**Comment by cgimenez** [comment] 2015-02-18 14:29
Followed the different advices in this discussion thread and examples run all fine on rpi2 with 084 stable armv7 openframeworks archive.

**Comment by PTS93** [comment] 2015-05-04 22:31
Having the same issue with the latest nigthly (https://github.com/openframeworks/openFrameworks/commit/b21fce7f69b1a06dfdb63555b389c2b589edfd50).
Weirdly it worked on an old but rather broken image. A new image I just setup doesn't work.
Running an rpi2 and have installed gcc 4.8.2. Running `gcc -v` yields `gcc version 4.8.2` aswell so that should work.
I can't pin down what I have in my old and broken image that the new image (using Raspbian 2015-02-16) has that made it work.
