### ISSUE TITLE
oxKinect - kinect id's not maintained

### ISSUE THREAD

**Issue by nosarious** [openframeworks/openFrameworks#2527] opened 2013-08-30 15:50 UTC
This is with Xcode on a mac mini, osx mountain lion.

I have two kinects in specific locations. The calibration is set up for where they are, and the settings are loaded for every start of the system. Theoretically, their location should not change with respect to the calibration because they are being identified with the id's:

for (int i=0; i<2; i++){
		kinect[i].close();
		kinect[i].init(false, false);
			//	kinect.setVerbose(true);
		kinect[i].open(i);
	}

(can't set tilt angle because it is not flat on a surface)

The problem is that they are not always referring to the proper coordinates as set in the calibration file for kinect[0] and kinect[1].

I am disconnecting them every night (putting my mac mini away) and reconnecting every morning, but occasionally they end up not being sorted properly. I am reconnecting them before I turn on the computer. I am unsure if this is the cause of the problem.

Out of twenty or so days working with this system, it has happened twice. I am trying to add a 'kinect id swap' to my calibration routine, but this means I can't assume the kinect locations will remain the same for large scale permanent installations.

**Comment by ofTheo** [comment] 2015-02-23 22:52
Actually just ran into this issue. 
The sorting is happening and device list is being sorted by serial number correctly. 

The issue is that opening via the ID is not opening with the now sorted index but the original bus id ( which is basically the order you plug the kinects in ). So the sorting is actually having no effect. 

Here are two cases where I plug in the same two kinects but in a different order. 

```
( i represents the sorted index in the vector ) 
[i = 0] sorted serial is A00367900545114A - id is 0
[i = 1] sorted serial is B00364705744105B - id is 1
```

```
[i = 0] sorted serial is A00367900545114A id is 1
[i = 1] sorted serial is B00364705744105B id is 0
```

Notice in the second list device B shows up with id 0 and device A has id 1. 
The devices are sorted correctly in the device list but calling `kinect.open(0);` will produce two different results as it matches against the id and not the index. 

So in the second scenario `kinect.open(0);` will actually open the second device in the device list and not the first. 

I believe this a bug as the whole point of doing the sorting was that calling kinect.open(0) would always open the same kinect regardless of the order it was enumerated in. 

The fix for this should be quite simple:

Change:

```	
	if(freenect_open_device(kinectContext, &kinect.kinectDevice, id) < 0) {
		ofLogError("ofxKinect") << "could not open device " <<  id;
		return false;
	}
```

to

```
	int index = getDeviceIndex(id); 
	if( index == -1 ){
		ofLogError("ofxKinect") << "could not open device " <<  id;
		return false; 
	}
	int sortID = deviceList[index].id; 
	if(freenect_open_device(kinectContext, &kinect.kinectDevice, sortID) < 0) {
		ofLogError("ofxKinect") << "could not open device " <<  id;
		return false;
	}

```

**Comment by nosarious** [comment] 2015-02-23 22:59
I, personally, built a system for unblinking/linking the kinects in the main code, mostly to allow people to use different models of kinects side-by-side. 

While an automagic system for red tarting the equipment due to power outages or accidental unplugging would have been preferred, an alternative was to include the ability to reset the kinects in software instead.

**Comment by danomatika** [comment] 2015-02-23 23:11
If that fix works, then it looks good to me.

**Comment by ofTheo** [comment] 2015-02-23 23:12
Thanks for the quick reply @danomatika !

It does seem to work ( and is actually non regressive as before it was basically random which kinect would open first ). 
I have a good setup for testing, so I'll do a bit more testing and then submit a PR.

**Closed** 2015-02-24 19:57 UTC
Labels: addon, bug
