### ISSUE TITLE
ofVideoGrabber+  RPI4 onboard camera only black and white

### ISSUE THREAD

**Issue by steeley** [openframeworks/openFrameworks#6581] opened 2020-04-29 14:32 UTC
OF 0.11, Buster RPI4, FKMS driver, Desktop.. Trying to get this working as ofxOMXCamera not usable on Pi4.

using the standard OF video grabber example works with the pi onboard camera, but
the frame rate is very slow, and it. looks like gstreamer is doing some sort of scaling.

if I do grabber.setPixelFormat(OF_PIXELS_NATIVE);
I get a good frame rate, low CPU no odd scaling but only black and white video. Also a little image tearing.
 How to fix? console output below.

```
 [notice ] ofGstVideoGrabber: Found device :, getting capabilities...
[notice ] ofGstVideoGrabber: detected v4l2 device: mmal service 16.1
[notice ] ofGstVideoGrabber: driver: bm2835 mmal, version: 267105
[notice ] ofGstVideoGrabber: Capabilities: 0x85200005
[notice ] 0: mmal service 16.1
[notice ] ofGstUtils: setPipelineWithSink(): 
gstreamer pipeline: v4l2src name=video_source device=/dev/video0 ! video/x-raw,framerate=24/1  ! appsink name=ofappsink enable-last-sample=0 caps="video/x-raw,
format={RGBA,BGRA,RGB,BGR,RGB16,GRAY8,YV12,I420,NV12,NV21,YUY2}, 
width=640, height=480"
[notice ] ofGstVideoUtils: allocating with 640x480 YUY2
```

**Comment by arturoc** [comment] 2020-05-05 13:04
when using OF_NATIVE_PIXELS you need to use the programmable renderer / opengl 3+ cause we do the colorspace conversion in the gpu which is not supported under the default fixed pipeline renderer. 

going to close this since it's not a bug, if you have any further questions please ask in the forum

**Closed by arturoc** 2020-05-05 13:04 UTC
