### ISSUE TITLE
Compilation oF failed on win10

### ISSUE THREAD

**Issue by MarionAudebert** [openframeworks/openFrameworks#5271] opened 2016-09-20 13:20 UTC
Hello everyone,
I have an issue when try to compile openframeworks on a comuter (win10, intel i3, x64, HD Graphics 3000).
I tried multiple times to redo the install of msys2, clean of directory, make clean, download master branch, but still the same error : 

`$ make
HOST_OS=MINGW32_NT-10.0
checking pkg-config libraries:   cairo zlib openssl glew glfw3
with PKG_CONFIG_LIBDIR=
HOST_OS=MINGW32_NT-10.0
checking pkg-config libraries:   cairo zlib openssl glew glfw3
with PKG_CONFIG_LIBDIR=
HOST_OS=MINGW32_NT-10.0
checking pkg-config libraries:   cairo zlib openssl glew glfw3
with PKG_CONFIG_LIBDIR=
Compiling /c/openFrameworks-master/libs/openFrameworks/3d/of3dPrimitives.cpp
/mingw32/bin/g++ -g3  -std=gnu++14 -DUNICODE -D_UNICODE -Wall -fexceptions -march=native -mtune=native -DPOCO_STATIC -mms-bitfields -IC:/msys64/mingw32/include/cairo -IC:/msys64/mingw32/include/pixman-1 -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include/freetype2 -IC:/msys64/mingw32/include/libpng16 -IC:/msys64/mingw32/include/harfbuzz -IC:/msys64/mingw32/include/glib-2.0 -IC:/msys64/mingw32/lib/glib-2.0/include -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include/freetype2 -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include/harfbuzz -IC:/msys64/mingw32/include/glib-2.0 -IC:/msys64/mingw32/lib/glib-2.0/include -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include/libpng16 -IC:/msys64/mingw32/include -I/c/openFrameworks-master/libs/fmodex/include -I/c/openFrameworks-master/libs/glm/include -I/c/openFrameworks-master/libs/glm/include/glm -I/c/openFrameworks-master/libs/glm/include/glm/detail -I/c/openFrameworks-master/libs/glm/include/glm/gtc -I/c/openFrameworks-master/libs/glm/include/glm/gtx -I/c/openFrameworks-master/libs/glu/include -I/c/openFrameworks-master/libs/json/include -I/c/openFrameworks-master/libs/kiss/include -I/c/openFrameworks-master/libs/rtAudio/include -I/c/openFrameworks-master/libs/tess2/include -I/c/openFrameworks-master/libs/utf8cpp/include -I/c/openFrameworks-master/libs/utf8cpp/include/utf8 -I/c/openFrameworks-master/libs/videoInput/include -I/c/openFrameworks-master/libs/openFrameworks -I/c/openFrameworks-master/libs/openFrameworks/3d -I/c/openFrameworks-master/libs/openFrameworks/app -I/c/openFrameworks-master/libs/openFrameworks/communication -I/c/openFrameworks-master/libs/openFrameworks/events -I/c/openFrameworks-master/libs/openFrameworks/gl -I/c/openFrameworks-master/libs/openFrameworks/graphics -I/c/openFrameworks-master/libs/openFrameworks/math -I/c/openFrameworks-master/libs/openFrameworks/sound -I/c/openFrameworks-master/libs/openFrameworks/types -I/c/openFrameworks-master/libs/openFrameworks/utils -I/c/openFrameworks-master/libs/openFrameworks/video -DDEBUG  -MMD -MP -MF /c/openFrameworks-master/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.d -MT/c/openFrameworks-master/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.o -o /c/openFrameworks-master/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.o -c /c/openFrameworks-master/libs/openFrameworks/3d/of3dPrimitives.cpp
make[2]: *** [makefileCommon/compile.core.mk:241: /c/openFrameworks-master/libs/openFrameworksCompiled/lib/msys2/obj/Debug/libs/openFrameworks/3d/of3dPrimitives.o] Error 1
make[1]: *** [makefileCommon/compile.core.mk:213: Debug] Error 2
make: *** [makefileCommon/compile.core.mk:229: all] Error 2
`

I also tried to compile on qtcreator but no result.
(More infos here : https://forum.openframeworks.cc/t/compiling-of-0-9-3-with-msys2-fails-on-windows-7/23885/12 )

Thanks for your help.
Marion

**Comment by nabetse** [comment] 2016-10-29 12:23
I was having the same problem. It worked for me when I use the latest MSYS2 in the repository instead of the one-click installer

**Comment by bakercp** [comment] 2017-05-22 20:13
Closing this as a duplicate of #5576

**Closed by bakercp** 2017-05-22 20:13 UTC
Labels: msys2
