### ISSUE TITLE
Remove using namespace std

### ISSUE THREAD

**Issue by abergmeier** [openframeworks/openFrameworks#2581] opened 2013-09-22 13:08 UTC
Including the whole C++ standard library is known to be very [bad practice](http://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice).

**Comment by tgfrerer** [comment] 2015-06-16 19:40
In an effort to show my enthusiasm for this, and after reading http://gotw.ca/gotw/053.htm
I've spent five hours this afternoon refactoring the whole of oF core so that it would work without having `using namespace std` in `ofConstants.h`.

Here's the branch: 

https://github.com/tgfrerer/openFrameworks/tree/core-explicit-std

* It's only been tested on vs2015RC, so it's well possible that other platforms still have one or the other `std::` missing.

--

I'd really love to see namespaces in 1.0, since it will allow oF to interact with a whole lot of other libraries more easily. One of the hardest things to figure out are namespace shadowing, and header file include order, things we could keep in check using namespaces. 

I ran into some collisions with pugixml recently, and debugging them was not pretty. Mostly, because the compiler errors are often meaningless when namespace clashes occur.

I've also read the [oF forum discussion from seven years ago](http://forum.openframeworks.cc/t/openframeworks-namespace/1006) and would suggest that with 1.0 oF could be at a point in maturity (and complexity) where namespaces will do more good than harm.

A change like this is makes a whole lot of older PRs un-mergeable (and will also, if un-merged itself, code-rot faster than you can say "namespace"), simply because it touches so many lines (and almost every core oF file), but I'll be happy to scrap this branch and restart the refactor feast again once we are at a point where the codebase changes less fast.

**Comment by bilderbuchi** [comment] 2015-06-16 20:58
+100 to this. I think if we merge after 0.9.0 release, we got enough time to iron out non-merging PRs and other wrinkles caused by this change.

**Comment by arturoc** [comment] 2015-06-16 20:58
i think we should merge this, we can re-import std from for example ofMain.h by now so everything outside the core keeps working as it is right now but the core or anything that doesn't include ofMain directly needs to import std manually.

**Comment by tgfrerer** [comment] 2015-06-16 21:28
Let me check this option tomorrow in my testing branch. 

I've grouped the commits in two - and I believe the better (and less intrusive way of doing this) would be to apply the changes to the header files, but in some of the cpp files add a `using namespace std;`

My hope would be that a PR would then touch less files, and merging would be simpler, and the git history less noisy. That said, I think it's good practice to add std:: to anything from the stl in core code.

**Comment by tgfrerer** [comment] 2015-06-17 09:48
I just tested this with `using namespace std;` in `ofMain.h`. It works. Here's what i found:

* ofApp.h + ofApp.cpp (userland code) work as they did (no need for the `std::` prefix). However, because ofMain.h is importing `std` into the global namespace, anything included after `ofMain.h` will have to deal with the "overpopulated" global namespace.
* This would mean that any external library had to be included before `ofMain.h`. That's in `main.cpp`, before the `#include "ofMain.h"` line.
* Addons which are well-behaved, i.e. don't include `ofMain.h` by default, need to have the `std::` prefix for every STL element in their header files. For their `.cpp` files, it's enough to add `using namespace std;` somewhere near the top for a quick fix. This should be fine, since `.cpp` files don't "infect" the global namespace, as header files do.

**Comment by danoli3** [comment] 2015-06-17 12:46
+10000 for removing ```using namespace std;``` in favour of an explicit ```std::*``` throughout the core with proposed fix by @tgfrerer.

It's the standard way ;P

**Comment by ofZach** [comment] 2015-06-17 12:51
+1 (add as many zeros as you want) I think this is definitely think this is a good move.  

I also support moving to using namespaces, it definitely feels like time.  I found a folder on an old drive that says OF 0.00 -- it has like 5 files in it  :)   I think alot of the older worry about namespaces was coming from a different place entirely and OF has matured and changed a great deal since then.

**Comment by tgfrerer** [comment] 2015-06-17 13:35
Brilliant! i guess, the next step would be to figure out if we want the change to happen before or after 0.9. I tend to *after* currently, so we can focus on getting the release out asap =)

**Comment by bilderbuchi** [comment] 2015-06-17 13:38
no, the next step is obviously to graduate from +1e4 to at least 1e9, to get to the next stage on the hype cycle. D:

anyway, yeah, I'd also vote for (right) after 0.9.0.

**Comment by ofTheo** [comment] 2015-06-17 15:35
I would be curious how namespaces in OF would look / work.
 
If it was simply to have an of:: namespace for the whole project I could see that being useful in terms of all the global enums we have and constants like PI etc. 

I would be curious to hear what people's ideal namespace scenario is and what problems would it be solving? Maybe in a separate issue?

**Comment by arturoc** [comment] 2015-06-17 16:02
i think we should begin with of:: and perhaps of::system for system utils since those are already ofSystem.... and of::fs or filesystem since we already have a name clash there with of::path for graphics path and of::fs::path for ofFilePath everything else should be in of:: directly i think

also we can bring parts of the std into of:: like std::filesystem could be of::fs or of::filesystem (that's fairly common practice) so will have of::fs::path, of::fs::file, of::fs::directory... 

also i would probably include all the of namespace when including ofMain.h which would make it easier for people to keep using string, vector... but also ofFilePath would be fs::path, ofFile fs::file... without having to add using namespace.  

more advanced users or if you have a problem of name clashing then you can include the needed headers only which won't bring all the namespace in. that would make life easier for both beginners and advanced users.

**Comment by ofTheo** [comment] 2015-06-17 16:59
I would also be fine keeping it simple i.e.: 
of::path
of::filepath / of::file / of::directory 

but yeah lets maybe address this after 0.9.0  :-)

**Comment by mitchmindtree** [comment] 2015-06-17 16:59
Big :+1: to all this name-spacing! Especially `of::`... beautiful and clean :)

**Comment by bilderbuchi** [comment] 2015-06-17 18:28
could also get rid of many of those `of*` names when switching to namespaces.

**Comment by kylemcdonald** [comment] 2015-06-19 16:45
i support merging @tgfrerer's branch, but i think we need to go all the way:

1. figure out what the error messages are for various pieces of "old" code that assumed `using namespace std` was present. check this on all the different compilers / IDEs we use.
2. post a thread to the OF forum that just says "if you are getting one of these errors: [list of errors] then at the top of your file write `using namespace std` or add `std::` to each line"

if we don't do this *before* the change is made, there will be fragmentation in how people fix the resulting bugs.

@ofZach i'd love a copy of that OF 0.00 folder. right now i only have OF 0.02, 0.03, 0.06 from the parsons site.

**Comment by tpltnt** [comment] 2015-06-30 20:42
@tgfrerer do you need help to ship stuff? I have a few spare cycles.

**Comment by bilderbuchi** [comment] 2015-07-01 09:13
see also #3517

**Comment by ToxicBananaParty** [comment] 2021-11-11 23:24
Is this ever going to happen?

**Comment by dimitre** [comment] 2022-05-26 13:30
I can update some core files to remove "using namespace std"

**Comment by dimitre** [comment] 2022-05-27 13:50
I've read some positive things about bringing in just some parts of std, like:
```c++
using std::swap;
using std::vector;
using std::map;
```
which can be substituted by some specialized version by the compiler (if they exist) 
ref : https://stackoverflow.com/a/1265068

**Comment by dimitre** [comment] 2022-05-31 23:25
Removed, I think this can be closed @ofTheo

**Comment by ofTheo** [comment] 2022-06-01 17:41
closed by #7005

**Closed** 2022-06-01 17:40 UTC
Labels: core, feature, development-strategy
