### ISSUE TITLE
Project Generator should be code signed on macOS

### ISSUE THREAD

**Issue by bangnoise** [openframeworks/openFrameworks#5975] opened 2018-04-18 16:57 UTC
Project Generator cannot be launched on stock macOS because it isn't code signed.

The distributed Project Generator should be code-signed. Telling users to downgrade their OS-wide security settings is a terrible solution from a usability or security standpoint.

of_v0.10.0RC1_osx_release and prior

**Comment by bangnoise** [comment] 2018-04-18 16:58
Previously discussed in #2649

**Comment by ofZach** [comment] 2018-04-23 14:09
another option (or in addition) is to code sign a dmg and distribute OF in that vs a zip.  The issues with the PG relate to "app translocation" in sierra+ and I've found using a signed dmg solves this -- it's a big issue I've had with clients recently.  in my case I use https://www.araelium.com/dmgcanvas but I'm sure there's a way to do this programmatically.

**Comment by arturoc** [comment] 2018-04-23 21:55
The PG is built in the CI servers: https://travis-ci.org/openframeworks/projectGenerator  and uploaded here: http://ci.openframeworks.cc/projectGenerator/

Then the create package script pulls it from there

**Comment by ofZach** [comment] 2018-04-24 00:25
one thing to consider is that the the thing that is getting built is the command line tool -- electron is compiled elsewhere and the command line tool is added to that -- we may need to look at something like this: 

https://github.com/electron-userland/electron-osx-sign
https://mintkit.net/electron-userland/electron-osx-sign/guide/

to sign the actual app 

at any rate, as a first fix attempt, I do think code signing a dmg that OF is distributed in (vs using an unsigned zip) would help, I am doing that right now on client projects where I have to send them an app and it helps a lot since the act of copying everything out of the signed dmg allows it to run without app translocation.

**Comment by arturoc** [comment] 2018-04-24 13:44
The ci server is now signing the electron app when building the project. Can you check that is working for you? http://ci.openframeworks.cc/projectGenerator/projectGenerator-osx.zip

If it's ok like that i'll modify the create packages script to pull that and see if that's enough or we need to also sign the final download as a dmg (which should be pretty straight forward now)

**Comment by ofZach** [comment] 2018-04-24 13:47
that didn't seem to work for me -- on first launch 

<img width="417" alt="screen shot 2018-04-24 at 9 45 24 am" src="https://user-images.githubusercontent.com/142897/39191205-74eca1b8-47a4-11e8-85ad-af9bbbbca052.png">

after going to security and manually enabling -- got this (running it inside OF) 

<img width="493" alt="screen shot 2018-04-24 at 9 46 36 am" src="https://user-images.githubusercontent.com/142897/39191233-82302728-47a4-11e8-82db-5917db212f77.png">

**Comment by ofZach** [comment] 2018-04-24 13:51
if helpful there's an app called RB checker on osx that checks signing
(https://apple.stackexchange.com/questions/82587/how-can-i-determine-if-a-certain-app-file-is-signed) 

it flags something: 

<img width="888" alt="screen shot 2018-04-24 at 9 50 14 am" src="https://user-images.githubusercontent.com/142897/39191469-fe4cbf24-47a4-11e8-8dc5-e3c21fd00673.png">

<img width="1560" alt="screen shot 2018-04-24 at 9 50 20 am" src="https://user-images.githubusercontent.com/142897/39191480-051648e8-47a5-11e8-8909-981e427aecb6.png">

**Comment by ofZach** [comment] 2018-04-24 13:51
I wonder if it's signed before we add the command line tool ?  or something we do to modify it after signing it...

**Comment by arturoc** [comment] 2018-04-24 14:02
i might be missing some parameter to the electron sign app to sign for production or something... going to take a look

**Comment by arturoc** [comment] 2018-04-24 15:32
It seems it was just that the zip compression was eating the symlinks, after adding a flag to preserve them it's working now fine, i can open the app right away after downloading and accepting to open a downloaded app

Even with that translocation still happens, it seems the only way to remove it is through running some xattr in the command line or moving the app, not even the containing folder but directly the .app somewhere else.

Any ideas?

**Comment by arturoc** [comment] 2018-04-25 09:50
So i've been trying several things but there's no way to solve translocation but moving the application itself somewhere else after uncompressing which won't work for us cause we need it inside the OF folder to be able to detect the OF install. I've tried to create a signed dmg but that doesn't even solve the signature problem for the PG unless the PG itself is signed and it even then it doesn't solve the translocation.

I think the only solution would be to manually create a pkg installer for every release that would ask you where to install OF and then move the PG inside the folder or run xattr to remove the translocation attribtue. A install script would also do i think but then pointing the PG to the OF installation the first time seems easier than any of those anyway.

I'm going to close this by now since the PG is now signed.

**Closed by arturoc** 2018-04-25 09:50 UTC

**Comment by ofZach** [comment] 2018-04-25 10:07
in my experience distributing OF in a signed disk image (dmg) is the answer to this problem -- I give clients that now instead of zips when I send apps and they copy the contents out of the disk image, which removes the app translocation.    Disk images can also contain things like graphics (background images, etc) and readme files etc -- most app you download via disk image will give you hints about installing it, OF could give you some advice about where to put it. 

I'm not sure how to code sign it on linux but here's a few links that might help 

https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform
https://stackoverflow.com/questions/23824815/how-to-add-codesigning-to-dmg-file-in-mac

**Comment by ofZach** [comment] 2018-04-25 10:09
for example (it's not pretty!) this is what I send to clients now

<img width="614" alt="screen shot 2018-04-25 at 6 08 12 am" src="https://user-images.githubusercontent.com/142897/39239525-227dd23e-484f-11e8-9de8-9c3e89660efc.png">

it's helped me a lot since app translocation meant I had to write long emails about moving .app files around, etc

**Comment by arturoc** [comment] 2018-04-25 10:10
I've tried signed dmg but it doesn't work. The problem is that OF is not an app but a folder with code... so a dmg just shows that folder, you copy it somewhere else but that doesn't disable translocation cause the app is inside the folder, you have to move the app itself for translocation to go away.

Here's a signed dmg if you want to try: http://ci.openframeworks.cc/versions/of_v20180424_osx_release.dmg

**Comment by arturoc** [comment] 2018-04-25 10:11
sorry in that one the PG is corrupted, let me upload a correct one

**Comment by arturoc** [comment] 2018-04-25 10:36
here: http://ci.openframeworks.cc/versions/of_v20180425_osx_release.dmg

**Comment by arturoc** [comment] 2018-04-25 10:39
but if doing a signed dmg solves it for you by packaging a whole folder, perhaps you can try to sign the latest nightly with the software you are using, there might be something i'm missing when doing it from the command line but for me signing the dmg without signing the PG app inside doesn't even solve the signature issue
