### ISSUE TITLE
ofVideoPlayer "unable to call GetConnectedMediaType" (Windows)

### ISSUE THREAD

**Issue by YuyQuan** [openframeworks/openFrameworks#5114] opened 2016-05-31 05:11 UTC
I attempted to load and play a simple mp4 file and this is was the log reads:
```
unable to call GetConnectedMediaType
[ error ] ofDirectShowPlayer:  Cannot load video of this file type.  Make sure you have codecs installed on your system.  OF recommends the free K-Lite Codec pack.

```
Despite being able to play mp4's on the the desktop, I downloaded the standard codec package from: http://www.codecguide.com/download_kl.htm

And it did nothing.

Here is the full code
```
void ofApp::setup(){
	vid.load("video.mp4");
        //vid.loadMovie("video.mp4");
}

//--------------------------------------------------------------
void ofApp::update(){
	vid.update();
}


void ofApp::draw(){
	vid.draw(100, 100);
}


void ofApp::keyPressed(int key){
	switch (key)
	{
	case 'a':
	
    	vid.play();
		break;

	default:
		break;
	}
}
```

and of course in ofApp.h there is
```
ofVideoPlayer vid;
```

**Comment by jvcleave** [comment] 2016-06-03 16:15
I had the same issue with 
Windows 8.1
VS2015
Quicktime installed
K-Lite Mega Codec Pack

I also got the same message when trying to run the compiled app on 
Win 10 
niNite Klite codecs

This was reproducible with videoPlayerExample and fingers.mov

**Comment by ofTheo** [comment] 2016-06-04 00:07
Can also confirm this issue! 

I think this might be to do with the fact the ffdirectshow filters are getting phased out from a lot of codec packages.  I remember I had similar issues when trying to select a codec package for us to recommend, a lot of them didn't work as they defaulted to LAV or WMF pipelines. 

My guess is that the K-Lite defaults changed and now the settings are not supporting directshow by default. That would explain why it worked a while ago, but now isn't working.  

The ideal fix would be to switch to a WMF pipeline which has been semi done with some of the ofxWMF addons ( https://github.com/secondstory/ofxWMFVideoPlayer ). I think some work would need to be done to get pixels back from the gpu. 

ping @DomAmato as he has the most up to date:  https://github.com/DomAmato/ofxWMFVideoPlayer

**Comment by DomAmato** [comment] 2016-06-04 19:37
its probably a better alternative than having people install codecs in the long run... I think when of0.9.0 was released that was the most common forum post for a few weeks. I believe the fork I have should have access to the pixels and texture though to be honest I rarely need access to either so I haven't tested it very much

**Comment by jvcleave** [comment] 2016-06-05 00:45
I just tried OF 0.83 and VS2012 and videoPlayerExample can play - something not 64bit compatible?

**Comment by DomAmato** [comment] 2016-06-05 00:47
quicktime

**Comment by subongjeong** [comment] 2016-06-19 05:45
Version 12.1.0 It works.
https://www.codecguide.com/download_kl_old.htm

**Comment by jvcleave** [comment] 2016-06-20 17:17
confirmed @subongjeong !

I used "Version 12.1.0 Full ~ 33.9 MB ~ April 18th 2016"

http://filehippo.com/download_klite_codec_pack/67445/

**Comment by ofTheo** [comment] 2016-07-07 15:34
@subongjeong @jvcleave I'll add a note then to the download instructions - but I think it might be worth moving to the WMF approach for the next release.

**Closed by ofTheo** 2016-07-07 15:34 UTC

**Comment by danzeeeman** [comment] 2016-07-08 14:52
I just tried this new codec pack on my windows 10 machine and now I can't play h264 videos with the DirectShow player

**Comment by ofTheo** [comment] 2016-07-08 16:27
@danzeeeman weird! 
does the video player example work? did you uninstall any other codec packs?

**Comment by ofTheo** [comment] 2016-07-08 19:31
@danzeeeman - I just doubled checked this on Windows 10. 

I installed the 12.10 Full K-Lite and set it up with the Simple setting option.  Didn't change any options except to not check for updates. 

The video player example works fine for me with this approach ( note: it didn't work when I changed the preferred decoder to ffdshow )

**Comment by ofTheo** [comment] 2016-07-08 20:02
@jvcleave @danzeeeman - actually I also just checked the nlite link in the setup instructions ( http://openframeworks.cc/setup/vs/ ) and that also works for me too.  ( I made sure to uninstall all other codecs and tested the videoPlayerExample to double-check ).  

Nlite grabs the latest version of K-Lite codecs, so my guess is that a recent version of K-Lite was broken for Directshow playback and a newer release is working again.  As when I first commented on this issue the Nlite codec was resulting in the error above.  

It would be great if you could try the nlite link and see if it works for you both. 
Thanks!

**Comment by danzeeeman** [comment] 2016-07-08 20:46
Let me try and uninstall everything and do the simple setup

**Comment by danzeeeman** [comment] 2016-07-08 20:54
OK simple install restored VideoPlayerExample but still not my 360VideoPlayer app.

**Comment by ofTheo** [comment] 2016-07-08 22:10
hmm strange - did that ever work with OF on windows? 
could you share a sample video that won't load?

**Comment by danzeeeman** [comment] 2016-07-08 23:03
I've never been able to play this video with the directshow player on windows.  it works well with the WMF addon on my machine and a modern one.  It's a huge 4k web optimized 264h in an mp4.  I might be able to send you the video to play with but it's like a 2GB+and not mine.  I can make another test video or clip out a part of this one to share.

**Comment by elliotwoods** [comment] 2016-10-13 05:59
suggest for interim changing:
https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/video/ofDirectShowPlayer.cpp#L1128

from:
```c++
        ofLogError("ofDirectShowPlayer") << " Cannot load video of this file type.  Make sure you have codecs installed on your system.  OF recommends the free K-Lite Codec pack. " << endl;
```
to
```c++
        ofLogError("ofDirectShowPlayer") << " Cannot load video of this file type.  Make sure you have codecs installed on your system.  OF recommends the free K-Lite Codec pack v12.1.0. Later versions which use the LAV codec may not work. " << endl;

```

**Comment by companje** [comment] 2016-10-19 07:46
Installing 12.1.0 worked for me but I couldn't find the setting 'not to check for updates.' during install. Can someone please post a screenshot where to look?
