### ISSUE TITLE
Using ofParameter with UI systems like ImGui.

### ISSUE THREAD

**Issue by yeswecan** [openframeworks/openFrameworks#5255] opened 2016-09-09 14:36 UTC
Hello there!
We're having trouble setting up a handy UI system with ofParameter (which we try to use now as it's official and we support oF). The problem is that it doesn't call its callbacks when changed by ImGui's with the following code:

```
ofParameter<float> par;

par.addListener(this, &ofApp::callback);

if (ImGui::SliderFloat("Float", (float*)&par.get(), par.getMin(), par.getMax()))
{
       // par.notifyChanged(); // we added this little function to ofParameter to call its callback manually
}

```
Apart from adding this `.notifyChanged()`, we couldn't figure out an elegant way to make it work. ImGui wants a pointer to a value as a parameter. Any advice on how to achieve this?

**Comment by arturoc** [comment] 2016-09-09 15:19
i'm going to close this as a duplicate of https://github.com/openframeworks/openFrameworks/issues/5109 and answer there

**Closed by arturoc** 2016-09-09 15:19 UTC

**Comment by yeswecan** [comment] 2016-09-09 15:28
@arturoc with all the respect, that's not the duplicate. I'm asking if there's any ideas how to modify ofParameter in order to process the callback, not how to get the pointer to actual data (which worked via (float*)&par.get()).

**Comment by arturoc** [comment] 2016-09-09 15:41
i think is similar enough that the i would have given the same answer to this issue too. there's no easy solution or anything that we could change in ofParameter to make it easily integrate with immediate mode guis or anything that takes a reference to the original data, but feel free to reopen it and add more info if you still think my answer there doesn't answer this too
