### ISSUE TITLE
Installing dependencies fails on Linux Mint 17

### ISSUE THREAD

**Issue by nventuro** [openframeworks/openFrameworks#4342] opened 2015-09-06 19:11 UTC
The lastest nightly build (http://192.237.185.151/versions/nightly/of_v20150905_linux64_nightly.tar.gz) fails on `install_dependencies.sh` under Linux Mint 17.1 Rebecca 64 bit.

The error message is:
```
The following packages have unmet dependencies:
 librtaudio-dev : Depends: libjack-dev
                  Depends: librtaudio4 (= 4.0.12~ds0-1ubuntu1) but it is not going to be installed
```

I managed to get it to run by manually doing:
```
sudo apt-get install librtaudio4
sudo apt-get install libjack0
sudo apt-get install libjack-dev
```

**Comment by bilderbuchi** [comment] 2015-09-06 19:46
ping @openframeworks/linux

**Comment by xionluhnis** [comment] 2015-10-29 21:20
I had the same issue as of the last master commit (https://github.com/openframeworks/openFrameworks/commit/2bb0fefc0c2486f2f74af540ece0b28445a69bb6) under Ubuntu 14.04 and those three extra dependencies made it work.

**Comment by arturoc** [comment] 2015-11-09 15:29
closing this since it's a duplicate of https://github.com/openframeworks/openFrameworks/issues/4546

**Closed by arturoc** 2015-11-09 15:29 UTC
Labels: bug, core, linux, section-internals
