### ISSUE TITLE
Bug ofxTCPServer::close 

### ISSUE THREAD

**Issue by thomasgeissl** [openframeworks/openFrameworks#4329] opened 2015-08-31 16:09 UTC
I cannot close a tcp server. Seems like there is a deadlock, caused by: https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxNetwork/src/ofxTCPServer.cpp#L56

I am on ubuntu 15.04. 

```c++
#include "ofMain.h"
#include "ofxNetwork.h"

class ofApp : public ofBaseApp{
        void setup()
        {
                _tcp.setup(11111);
        }
        void exit()
        {
                _tcp.close();
        }

        ofxTCPServer _tcp;
};
int main(  int argc, char *argv[]  ){
        ofSetupOpenGL(1024,768, OF_WINDOW);
        ofRunApp( new ofApp());
}

```

**Comment by bilderbuchi** [comment] 2015-08-31 16:39
ping @arturoc

**Comment by ofTheo** [comment] 2015-09-02 10:56
I'm able to reproduce this on OS X. 
Both in exit() and ~ofApp() destructor. 

The app hangs on the mutex.lock() call.

**Comment by admsyn** [comment] 2015-09-14 04:00
I don't think it's just on exit, looks like it deadlocks immediately? It's visible on the main thread on exit though, since the destructor tries to grab the mutex that's already being deadlocked on.

[The issue is in `isClientSetup()` / `isClientConnected()`](https://github.com/openframeworks/openFrameworks/blob/621876270b585498e4557eacddf8afc60ffdb8b5/addons/ofxNetwork/src/ofxTCPServer.cpp#L280-L289). `isClientConnected()` locks the mutex and calls `isClientSetup()`, which tries to lock the same mutex. This is called from ofxTCPServer's threadedFunction.
```
//--------------------------
bool ofxTCPServer::isClientSetup(int clientID){
	std::unique_lock<std::mutex> Lock( mConnectionsLock );
	return TCPConnections.find(clientID)!=TCPConnections.end();
}

//--------------------------
bool ofxTCPServer::isClientConnected(int clientID){
	std::unique_lock<std::mutex> Lock( mConnectionsLock );
	return isClientSetup(clientID) && getClient(clientID).isConnected();
}
```

It can be fixed by taking out the lock in `isClientConnected()`, since both `isClientSetup()` and `getClient(...)` will themselves lock the mutex. It introduces a race condition if something were to happen in between those two calls, but I'm not really familiar enough with ofxTCPServer to know if that's something that matters in practice.

**Comment by galsasson** [comment] 2015-09-14 13:32
Same issue: #3580

**Closed** 2015-09-14 15:20 UTC
Labels: addon, bug, regression
