### ISSUE TITLE
ofVerticalSync(true) broken on macOS 10.14 + XCode 10.0

### ISSUE THREAD

**Issue by kylemcdonald** [openframeworks/openFrameworks#6146] opened 2018-10-06 01:02 UTC
Using the latest OF from Github.

I don't know which version of XCode, OF, or macOS created this problem.

Here's a simple example that should take 4 seconds for a line to walk across the screen from left to right:

```c++
#include "ofMain.h"

class ofApp : public ofBaseApp {
public:
    void setup() {
        ofSetVerticalSync(true);
        ofBackground(0);
    }
    void update() {
    }
    void draw() {
        ofDrawRectangle(ofGetFrameNum() % 240, 0, 1, 240);
    }
};

int main() {
    ofSetupOpenGL(240, 240, OF_WINDOW);
    ofRunApp(new ofApp());
}
```

Instead, it runs much faster, similar to how apps would run without a framerate limit when they are in the background/not in focus.

**Comment by ofTheo** [comment] 2018-10-06 01:11
Oh weird. What do you get if you print out the framerate?

**Comment by roymacdonald** [comment] 2018-10-06 03:05
Hi. I am not seeing this problem on macosx 10.12.6, xcode8.3.2 and newst OF from github. hope this helps somehow

**Comment by kylemcdonald** [comment] 2018-10-06 18:19
@ofTheo depends on the size of the window.

<img width="73" alt="screen shot 2018-10-06 at 11 19 15" src="https://user-images.githubusercontent.com/157106/46574537-b7ef8480-c959-11e8-9dfb-219338c395eb.png">
<img width="640" alt="screen shot 2018-10-06 at 11 18 50" src="https://user-images.githubusercontent.com/157106/46574538-b9b94800-c959-11e8-9293-85e10ed3bb3f.png">

**Comment by ofTheo** [comment] 2018-10-06 18:43
What if you call ofSetVerticalSync(true) every frame?  

It's looking like GL/ Window calls aren't working on the first frame / ofApp::setup

**Comment by kylemcdonald** [comment] 2018-10-18 14:02
@ofTheo calling it every frame doesn't work.

I also tried manually doing this:

```c++
#ifdef __APPLE__
    GLint                       sync = 1;
    CGLContextObj               ctx = CGLGetCurrentContext();
    CGLSetParameter(ctx, kCGLCPSwapInterval, &sync);
#endif
```

Both in `setup()` and on every frame in `draw()`, and that doesn't fix it either.

**Comment by ofTheo** [comment] 2018-12-11 23:23
Moving the discussion about vsync here as it still seems broken even in 10.14.2 

Looks like its being discussed in the GLFW issues too: 
https://github.com/glfw/glfw/issues/1337 

If a fix isn't apparent we could maybe default to ofAppRunner capping the frame rate at 60 fps. 

One of the issues reported this was an issue with the discrete card only. 
Curious if either @kylemcdonald or @ofZach  can reproduce with gfxCardStatus.

**Comment by ofZach** [comment] 2018-12-24 13:20
just a note that there seems to be some progress on solving this (in SDL but also discussion on GLFW): 

https://github.com/glfw/glfw/issues/1337
https://hg.libsdl.org/SDL/rev/73f3ca85ac0e

**Comment by ofZach** [comment] 2019-01-15 14:56
@ofTheo this looks promising https://github.com/glfw/glfw/pull/1417

**Comment by arturoc** [comment] 2019-03-07 12:00
seems this will finally be fixed in next macos update: https://twitter.com/FlohOfWoe/status/1103296098834305026

**Comment by ofTheo** [comment] 2019-08-07 17:33
yes - this is fixed now! 🙏

**Closed by ofTheo** 2019-08-07 17:33 UTC
