### ISSUE TITLE
vs apps report wrong scancodes for key presses

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#3960] opened 2015-06-18 12:12 UTC
On windows, i get the wrong scancodes for key presses.

here's a minimal testcase: https://gist.github.com/tgfrerer/77cbd9e2a60acc95ee1f

When i press lowercase `a`, then uppercase `A` I get:

	[notice ] key press   :    97
	[notice ] key released:    -1
	[notice ] key press   :    2304
	[notice ] key press   :    2305
	[notice ] key press   :    2304
	[notice ] key press   :    2305
	[notice ] key press   :    2304
	[notice ] key press   :    2305
	[notice ] key press   :    2304
	[notice ] key press   :    2305
	[notice ] key press   :    65
	[notice ] key released:    -1
	[notice ] key released:    2304
	[notice ] key released:    2305

I'm not sure what happens, but the high integer scancode (and -1 for key released) suggests that glfw for vs was not compiled with @arturoc's unicode patches from @ofTheo's [repo](https://github.com/ofTheo/glfw/archive/feature-keysUnicode.tar.gz) but straight from their repo. 

I've checked the vs apothecary recipe, but that seems ok.

**Comment by arturoc** [comment] 2015-06-18 12:29
it's probably been compiled from my repo since otherwise it won't compile. i think the problem is the merge from glfw master into my repo that @igiso sent some time ago. i merged it thinking it was well tested but i think it was only tested in osx and broke all other platforms. i was just going to keep the old version in linux since it doesn't have any issues but if it's failing in windows too i'll need to redo the patch

**Comment by tgfrerer** [comment] 2015-06-18 12:33
Hmm. Apothecary links to / downloads from @oftheo's repository. Would we need to update this, too?


typed on tocuh

**Comment by ofTheo** [comment] 2015-06-18 12:44
the link can point back to @arturoc 's repo ( https://github.com/arturoc/glfw/tree/feature-keysUnicode )  as he merged in the PR for the disappearing mouse on OS X issue. 

I've been using this version of GLFW in a project and it seems to work well on OS X. 
Ideally though we should try and get the keyscan issue fixed in GLFW so we can point apothecary to glfw/stable or glfw/master

**Comment by tgfrerer** [comment] 2015-06-19 11:55
Ok, I think i found the lines that did it, they are in [this switch branch](https://github.com/glfw/glfw/compare/master...arturoc:feature-keysUnicode#diff-bee1cd5e5316d5bf136cbaddbcd3b95eL344).

@arturoc I've sent your feature branch a PR: https://github.com/arturoc/glfw/pull/5

If you re-generate the archive and we point glfw back to `https://github.com/arturoc/glfw/archive/feature-keysUnicode.tar.gz` in apothecary i can re-generate the static lib and push the fixed version upstream.

**Comment by bilderbuchi** [comment] 2015-06-20 20:12
closed by #3969

**Closed by bilderbuchi** 2015-06-20 20:12 UTC
Labels: critical, regression, windows
