### ISSUE TITLE
ofSetColor(ofFloatColor) down-samples back to 8 bit

### ISSUE THREAD

**Issue by armadillu** [openframeworks/openFrameworks#5421] opened 2017-01-19 20:55 UTC
I'm making very slow trail effects, and i'm noticing a hard limit at 0,0039 alpha values when playing with float fbo's. This also happens to be 1 / 256, so looking into ofSetColor() it converts back to ofColor (char) no matter what you feed it (ofColor or ofFloatColor).

Also found an old forum post about this;

https://forum.openframeworks.cc/t/incorrect-float-colors-gl-rgba32float-fbos-banding/21200/2

**Comment by danoli3** [comment] 2017-01-19 21:59
Oh shiiit yeah that's a pretty big bug!

**Comment by arturoc** [comment] 2017-01-19 22:56
probably ofSetColor should only accept ofFloatColor everything else will convert to that but ofFloatColor will stay as it is, then the renderers should set it as floats

**Comment by dimitre** [comment] 2023-03-31 00:07
I suppose this one wasn't touched yet. for me it is the most serious issue in OF.

**Comment by dimitre** [comment] 2023-03-31 00:08
cc: @ofTheo @NickHardeman @artificiel

**Comment by artificiel** [comment] 2023-03-31 17:05
@arturoc's suggestion is of course the right direction but there might be a slight can of worms as `ofStyle` defines `.color` as `ofColor,` and is written as such (char) beside the calls to `glColor4f()`.

I think the proper solution would also need upgrading `ofStyle.color` (and `.bgColor`) to `ofFloatColor`? which will probably reveal more stuff... It might be a far-ranging project. 

but I agree probably necessary. with 10-bit color becoming more and more accessible, perhaps the float usage should become more encouraged (I find myself often working in float to keep the same brain state with shaders; the only advantage to 8-bit is the familiarity (and proliferation of the pattern due to web colours)).

https://github.com/openframeworks/openFrameworks/blob/b369a1861ee0bd82973fe85adafc93054fbd21dd/libs/openFrameworks/gl/ofGLRenderer.cpp#L1058-L1080

**Comment by artificiel** [comment] 2023-08-31 03:58
just took another look and the implications are far-reaching, e.g:
https://github.com/openframeworks/openFrameworks/blob/b818ea0304a0c442239fa3bf0a25e85f608fcc39/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L330-L334
so for things to be homogenous ofPath needs to be retouched... it basically means reworking all internal use of `ofStyle` to expect/respect `ofFloatColor`. (otherwise it would be a half-done upgrade, if something like ofPath color stays 8 bits)

not unfeasible, but quite something to test/validate, that should be executed by someone familiar with the code and equipped to make decisions across the renderers, as there are probably things along the way that will need some finesse. (it's not a simple search/replace hack).

so in essence it means a committed volunteer... (a bit like the iOS orientation "fiasco"...)

**Comment by NickHardeman** [comment] 2023-09-07 02:02
Changing to ofFloatColors internally seems achievable, though extensive, as @artificiel  mentioned.
If `ofSetColor( ofColor )` was changed to `ofSetColor(ofFloatColor)` the other ofSetColor functions should accept floats and values from 0-1 as ofFloatColor does. I think it would be confusing that the `ofSetColor(int)` functions changed from 0-255 to 0-1. This would cause a lot of previous projects to have strange colors: `ofSetColor( 1 )` would now be white instead of almost black as before. 
https://github.com/openframeworks/openFrameworks/blob/6f5baa10d286f49141dbe1086ffc503b19656e18/libs/openFrameworks/graphics/ofGraphics.h#L55-L58
For clarity, maybe adding functions appended with an F or something to differentiate from the previous functions like `ofSetColorF( ofFloatColor )` and `ofSetColorF( 1.f, 1.f, 1.f, 1.f );` etc. would be more explicit to hopefully avoid some confusion and previous projects should not see a change in output if using `ofSetColor( int );` etc.

```
void ofSetColorF(float r, float g, float b, float a); 
void ofSetColorF(const ofFloatColor & color); 
void ofSetColorF(const ofFloatColor & color, float _a); 
void ofSetColorF(float gray); 
```

**Comment by artificiel** [comment] 2023-09-07 05:12
perhaps ofSetFloatColor()? it maintains the name without introducing a new pattern.

but also perhaps use an overload to distinguish floats? such as:
```c++
void ofSetColor(int v) {
  ofSetColor(v/255.0f);
}
void ofSetColor(float v) {
  ofSetColor(v,v,v,1.0f);
}
// designated "final" ofSetColor moves to floats:
void ofSetColor(float r, float g, float b, float a = 1.0f) {
  ofGetCurrentRenderer()->setColor(r,g,b,a);
}
```
and non-withstanding the user interface, the Renderer interface becomes float, and all the funny business of doing /255.0 in GLRenderer can be removed.

that would throw off someone currently passing floats to ofSetColor and expecting them to be cast to 0-255 int range, but the OF sources are clean (either passing ints or ofColors); a quick search in GitHub finds some instances in user code, but it's often`ofSetColor(1.0,1.0,1.0,1.0);` like:

https://github.com/Daandelange/karmaMapper/blob/274b694f61d1a09e2e58c219d4232344ffceb49e/src/effects/shaderEffect/shaderEffect.cpp#L137

which looks like a form of GL reflex as the author seems to expects white (and on top of things the above converts to an alpha of 0.0039 too).

**Comment by NickHardeman** [comment] 2023-09-07 15:18
HI @artificiel,
Thank you for the suggestions.
`ofSetFloatColor` vs `ofSetColorF` maintains the OF naming convention seems like the better option. 

Not sure the overloading would be explicit enough as `ofSetColor(1.0);` would be interpreted as a double? I assume that would go to the float overload. And previous projects would be expecting 0-255 (mostly ;).
 
Another option could be similar to how vectors are handled.
https://github.com/openframeworks/openFrameworks/blob/6f5baa10d286f49141dbe1086ffc503b19656e18/libs/openFrameworks/math/ofMathConstants.h#L6-L17

ofClear( ); accepts floats, but should be in 0-255 range, which is confusing.
https://github.com/openframeworks/openFrameworks/blob/6f5baa10d286f49141dbe1086ffc503b19656e18/libs/openFrameworks/graphics/ofGraphics.h#L254

https://github.com/openframeworks/openFrameworks/blob/6f5baa10d286f49141dbe1086ffc503b19656e18/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L900-L903


I prefer the ofSetFloatColor approach to avoid breaking previous projects or add-ons that have been expecting the 0-255 range whether they are passing in `ints` or `floats` or `double`

I have already converted everything internally to use `ofFloatColor;` ie ofPath, ofStyle, and the renderers, etc. Based on a few tests it seems the same, but interfacing with setting the color is the hold up (ie. ofSetColor, ofBackground, ofClear); 

Hopefully I can send a PR in the coming days as it requires A LOT more testing.

**Comment by artificiel** [comment] 2023-09-07 19:50
indeed ofClear should have the same interface as ofSetColor (no /255.0 should remain within the Renderer).

there are some lingering issues around ofClear/ofBackground -- perhaps take the refactor occasion to take whatever insight from them in order to be able to close them? https://github.com/openframeworks/openFrameworks/issues/7057 https://github.com/openframeworks/openFrameworks/issues/264

**Comment by artificiel** [comment] 2023-09-07 19:55
also see https://github.com/openframeworks/openFrameworks/issues/3566

do we need something like ofClearWithFloatColor (and then even deprecate ofClear -> ofClearWithColor??)

**Comment by ofTheo** [comment] 2023-09-07 22:24
I do like: `ofSetFloatColor` as an approach as we then don't have to worry about breaking anything old. 

` void ofClear(float r, float g, float b, float a=0); ` should maybe become: 
` void ofClear(int r, int g, int b, int  a=0); `  ( not unsigned char to avoid unintentional wrapping / regression ) 

with two other options:

`void ofClear( const ofColor & clearColor );`
`void ofClear( const ofFloatColor & clearColor );`

Would that solve it all?

**Comment by NickHardeman** [comment] 2023-09-08 02:27
Changing `void ofClear(float r, float g, float b, float a=0);` to `void ofClear(int r, int g, int b, int  a=0);` Might lose some resolution if previous projects were passing floats in the range 0-255

As mentioned in #264 the arguments in `ofClear()` are inconsistent and the default alpha is 0. 

Following `ofSetColor()` regarding arguments and changing the default alpha from 0 to 255 or 1.f respectively ie. 
So ofClear would remain in the 0-255 range and ofClearFloat would be 0-1
```
void ofClear(float r, float g, float b);
void ofClear(float r, float g, float b, float a);
void ofClear(float brightness, float _a);
void ofClear(float brightness );

void ofClearFloat(float r, float g, float b);
void ofClearFloat(float r, float g, float b, float a);
void ofClearFloat(float brightness, float _a);
void ofClearFloat(float brightness);
```

**Comment by NickHardeman** [comment] 2023-09-09 03:16
Submitted #7650 
I have tested some of the graphics examples on an M1 running Ventura 13.3.1 and everything appears to be the same. But should be tested quite a bit more.

**Closed** 2023-09-22 01:26 UTC
Labels: critical
