### ISSUE TITLE
QTCreator Fails to build computer_vision examples with opencv4.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/openFrameworks#6334] opened 2019-07-10 01:07 UTC
There is a linker problem when compiling the opencv examples using QTCreator 4.6.1 and opencv4.  The QTCreator files were created using the import wizard.

The linker error indicates that a reference to symbols that should be in `opencv_objdetect`.

The same project compiles and runs just fine with the make files on the command line.

Here's the output.

```console
/usr/bin/g++ -Wl,-m,elf_x86_64,-fuse-ld=gold,-L/usr/local/lib -m64 -o /openFrameworks/examples/computer_vision/opencvHaarFinderExample/bin/opencvHaarFinderExample_debug /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvColorImage.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvContourFinder.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvFloatImage.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvGrayscaleImage.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvHaarFinder.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvImage.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/e09ae728c6a208b7/ofxCvShortImage.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/f27fede2220bcd32/main.cpp.o /openFrameworks/examples/computer_vision/build-opencvHaarFinderExample-Desktop-Debug/qtc_Desktop_Debug/opencvHaarFinderExample.33c745cb/f27fede2220bcd32/ofApp.cpp.o /openFrameworks/libs/openFrameworksCompiled/lib/linux64/libopenFrameworksDebug.a /openFrameworks/examples/computer_vision/opencvHaarFinderExample/../../../libs/fmodex/lib/linux64/libfmodex.so /openFrameworks/examples/computer_vision/opencvHaarFinderExample/../../../libs/kiss/lib/linux64/libkiss.a /openFrameworks/examples/computer_vision/opencvHaarFinderExample/../../../libs/tess2/lib/linux64/libtess2.a -lopencv_gapi -lopencv_stitching -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cudabgsegm -lopencv_cudafeatures2d -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_quality -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_cudacodec -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_videostab -lopencv_cudaoptflow -lopencv_optflow -lopencv_cudalegacy -lopencv_video -lopencv_cudawarping -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_imgproc -lopencv_cudaarithm -lopencv_core -lopencv_cudev -lharfbuzz -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lGLEW -lGLU -lGL -lglfw -luriparser -lcurl -lrtaudio -lasound -lpulse-simple -lpulse -lmpg123 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lglut -lX11 -lXrandr -lXxf86vm -lXi -lXcursor -lXinerama -ldl -lpthread -lfreeimage -lpugixml -lboost_filesystem -lboost_system
/openFrameworks/addons/ofxOpenCv/src/ofxCvHaarFinder.cpp:76: error: undefined reference to 'cv::CascadeClassifier::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/openFrameworks/addons/ofxOpenCv/src/ofxCvImage.cpp:660: error: undefined reference to 'cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
Process failed with exit code 1.
The following products could not be built for configuration qtc_Desktop_Debug:
opencvHaarFinderExample
Error while building/deploying project opencvHaarFinderExample (kit: Desktop)
When executing step "Qbs Build"
18:37:46: Elapsed time: 00:15.
```

**Comment by arturoc** [comment] 2019-07-10 15:25
on linux?

**Comment by bakercp** [comment] 2019-07-10 16:06
Yes, sorry.  Linux Mint. I haven't tried it on other platforms.

- Linux Mint 19.1 Tessa / aka Ubuntu 18.04
- gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

**Comment by arturoc** [comment] 2019-07-10 16:11
this sounds like either a compiler version mismatch (cause both libraries involve string) but not sure why it would work with makefiles. i'll try to reproduce it myself when i have a moment

**Comment by neilmendoza** [comment] 2020-01-20 20:51
I just ran into the same problem. OpenCV 4.1.2, gcc 7.4.0 and Ubuntu 18.04...

```
/home/jepson/of_v0.11.0_linux64gcc6_release/addons/ofxOpenCv/src/ofxCvHaarFinder.cpp:77: error: undefined reference to 'cv::CascadeClassifier::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/jepson/of_v0.11.0_linux64gcc6_release/addons/ofxOpenCv/src/ofxCvImage.cpp:660: error: undefined reference to 'cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int)'
collect2: error: ld returned 1 exit status
```

**Comment by ofTheo** [comment] 2021-01-19 22:23
@neilmendoza @bakercp do you think you could check with the nightly builds and see if this is still an issue?
Nightly builds are now compiled with `gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~16.04)`

**Comment by neilmendoza** [comment] 2021-01-20 11:27
Hi! I don't actually have a Linux box around at the moment. Will try it out when I have one set up.

**Comment by arturoc** [comment] 2021-01-21 18:55
This is working for me without problem after running install_dependencies.sh

Some time ago I included a fix in install_dependencies that changes opencv's addons_config.make to support opencv4 if that's detected in the system but the default is still 3. perhaps we should now change the script to do the opposite. the addons config should be setup by default to support opencv 4 and the script should change it to support 3 if opencv 3 is detected in the system

**Comment by ofTheo** [comment] 2021-01-21 20:18
Great! It also worked for me on two different 20.04 setups. 

Ah so basically changing the logic of this line: 
https://github.com/openframeworks/openFrameworks/blob/patch-release/scripts/linux/ubuntu/install_dependencies.sh#L228 

To search for opencv and not opencv4  and then flipping the logic below that?

**Comment by arturoc** [comment] 2021-01-22 10:48
Actually i'm checking the addon config https://github.com/openframeworks/openFrameworks/blob/patch-release/addons/ofxOpenCv/addon_config.mk#L63-L85  and it's already defaulting to opencv4 for linux64 and linux arm7. i think linux arm6 (rPi) still has opencv3 but in case it's already updated we can change the addon config.

The install_dependencies script is already doing the right thing no matter what so no need to change it in any case.

Going to close this since it seems this is already fixed

**Closed by arturoc** 2021-01-22 10:48 UTC
