### ISSUE TITLE
openFrameworks serial communicaton 

### ISSUE THREAD

**Issue by DataPaulette** [openframeworks/openFrameworks#5062] opened 2016-04-19 15:51 UTC
I'm using Teensy 3.1 to stream sensors values to openframeworks. I have an issue with openframeworks serial configuration. I don't receive any data from the serial port. If I open the Arduino serial monitor after that my openframeworks programme start to read correctly all the data. How can I modify the ofSerial.cpp file to have the same configuration than Arduino serial monitor?

I also posted this issue on teensy forum :  https://forum.pjrc.com/threads/34165-openFrameworks-serial-communicaton

**Comment by bakercp** [comment] 2016-04-19 15:56
Have you tried ofxSerial? I'm using it successfully with a teensy 3.1 as I
write.

**Comment by DomAmato** [comment] 2016-05-26 19:44
also can you tell the os and of version you are using?

**Comment by DataPaulette** [comment] 2016-05-28 14:32
Distributor ID:	Ubuntu
Release:	15.10
Codename:	wily

**Comment by bakercp** [comment] 2017-05-22 21:20
I cannot reproduce this issue.  Closing for now.

**Closed by bakercp** 2017-05-22 21:20 UTC
