### ISSUE TITLE
Poco::SystemException in ofxOscParameterSync() destructor

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#3104] opened 2014-07-24 15:28 UTC
On destructing ofxOscParameterSync(), I'm getting the following error:

```
terminate called after throwing an instance of 'Poco::SystemException'
  what():  System exception
```

The offending line appears to be this on line 17 of ofxOscParameterSync:
```
ofRemoveListener(syncGroup->parameterChangedE,this,&ofxOscParameterSync::parameterChanged);
```
Removing this line avoids the exception.
I'm not sure why this is happening...the ofRemoveListener call seems legit.

**Comment by admsyn** [comment] 2015-03-14 20:09
I can't reproduce this, at least not with a minimal setup. There's been a fair amount happening w/r/t event listening lately so it's possible this got silently fixed in the process? Here's my minimal repro attempt nonetheless:

```cpp
#include "ofMain.h"
#include "ofxOscParameterSync.h"

struct ofApp : public ofBaseApp {
	
	void setup() {
		params.setName("Params");
		resetSync();
	}
	
	void resetSync() {
		sync = shared_ptr<ofxOscParameterSync>(new ofxOscParameterSync);
		sync->setup(params, 8080, "localhost", 8081);
	}
	
	void keyPressed(int key) {
		resetSync();
	}
	
	ofParameterGroup params;
	shared_ptr<ofxOscParameterSync> sync;
};

int main( ){
	ofSetupOpenGL(320,240,OF_WINDOW);
	ofRunApp(new ofApp());
}
```

**Comment by bilderbuchi** [comment] 2015-06-17 13:23
@pierrep can you still reproduce this on latest master?

**Comment by ofTheo** [comment] 2015-06-17 14:22
I get this issue with current master. 

console message is:
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

![screen shot 2015-06-17 at 10 21 56 am](https://cloud.githubusercontent.com/assets/144000/8209403/b9f1ae52-14da-11e5-9c62-28717add4c28.png)

**Comment by bilderbuchi** [comment] 2015-06-17 14:29
pinging @arturoc

**Comment by ofTheo** [comment] 2015-06-17 14:36
yeah I see this with Xcode 6.01 and 6.1 - really not sure what is causing it. 
Maybe the order of destruction?

**Comment by ofTheo** [comment] 2015-06-17 14:38
changing 

```
		ofxOscParameterSync sync;

		ofParameter<float> size;
		ofParameter<int> number;
		ofParameter<bool> check;
		ofParameterGroup parameters;
		ofParameter<ofColor> color;
		ofxPanel gui;
```

to 

```

		ofParameter<float> size;
		ofParameter<int> number;
		ofParameter<bool> check;
		ofParameterGroup parameters;
		ofParameter<ofColor> color;
		ofxPanel gui;
    
		ofxOscParameterSync sync;
```

in ofApp.h stops the crash -

**Comment by ofTheo** [comment] 2015-06-17 14:42
Hmm I bet the issue is simply that syncGroup which is ofParameterGroup parameters; has been deleted as things higher up are deleted first. So syncGroup in ofxOscParameterSync is a pointer to a deleted object - hence the crash

```
ofxOscParameterSync::~ofxOscParameterSync(){
	if(syncGroup)
		ofRemoveListener(syncGroup->parameterChangedE,this,&ofxOscParameterSync::parameterChanged);
}
```

**Comment by tgfrerer** [comment] 2015-06-17 14:48
That would make sense - the order in which members are declared in cpp determines the order in which they will be deleted. Could it make sense to use `weak_ptr` instead of shared_ptr there, to not propagate ownership?

**Comment by ofTheo** [comment] 2015-06-17 14:50
Thats partially the problem. Its a regular pointer
```
	ofParameterGroup * syncGroup;
```
So there isn't a way to do weak_ptr without making the user use shared_ptr <ofParameterGroup> in ofApp

**Comment by arturoc** [comment] 2015-06-17 15:07
the parameter group acts as a shared_ptr already so we just need to make a copy instead of store a pointer. i'll fix it

**Comment by caodepalha** [comment] 2015-06-17 15:08
constantly receiving email from this and cannot unsubscrive

2015-06-17 16:07 GMT+01:00 arturo <notifications@github.com>:

> the parameter group acts as a shared_ptr already so we just need to make a
> copy instead of store a pointer. i'll fix it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/3104#issuecomment-112836375>
> .
>



-- 
Cumprimentos
Mauro Fernandes

917777142 /  927173680

**Comment by ofZach** [comment] 2015-06-17 15:15
@caodepalha maybe this can help 

https://help.github.com/articles/watching-repositories/
https://help.github.com/articles/configuring-notification-delivery-methods/ 

you have to unwatch this repo or change your alerts in github

**Comment by caodepalha** [comment] 2015-06-17 15:17
thanks

2015-06-17 16:15 GMT+01:00 ofZach <notifications@github.com>:

> @caodepalha <https://github.com/caodepalha> maybe this can help
>
> https://help.github.com/articles/watching-repositories/
> https://help.github.com/articles/configuring-notification-delivery-methods/
>
> you have to unwatch this repo or change your alerts in github
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/openFrameworks/issues/3104#issuecomment-112839735>
> .
>



-- 
Cumprimentos
Mauro Fernandes

917777142 /  927173680

**Closed** 2015-06-18 11:23 UTC
Labels: addon, bug, critical, prelim-analysis

**Comment by caodepalha** [comment] 2016-11-24 16:52
rolleiflexlx@gmail.com sent you an invitation to join MEGA.

--- Message from user: ---

---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDA1YTk4M2QwZDhkYTQ1ODU3ZjkxZjE4NzBhZDdlMWU0ZDU5Nzk1MTA1YWQ4N2U1OTJjZjAwMDAwMDAxMTE5OTRmMjU5MmExNjljZTAyNGRhNTNhQHJlcGx5LmdpdGh1Yi5jb2107vWUJogVWw

Best regards,

Team MEGA

**Comment by caodepalha** [comment] 2016-11-24 16:52
rolleiflexlx@gmail.com sent you an invitation to join MEGA.

--- Message from user: ---

---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDA1YTk4M2QzNjA5MjliMzFjYzMzMjcwZGJhMDcyZTczODE5NjU0MTcwYTcwMGQyOTJjZjAwMDAwMDAxMTE5OTUxMTE5MmExNjljZTAyNGRhNTNhQHJlcGx5LmdpdGh1Yi5jb22NvhkGP4KVmA

Best regards,

Team MEGA
