### ISSUE TITLE
ofVec2f::average not checking if one of the params is zero.

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#1555] opened 2012-09-06 14:32 UTC
inline ofVec2f& ofVec2f::average( const ofVec2f* points, int num )

num could come come in as zero.
need to check if zero and handle.

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/math/ofVec2f.h#L609-619

**Comment by bakercp** [comment] 2016-01-24 22:26
I'd argue that we should be using std::size_t instead of int here. That would prevent us from having to throw an exception (which is, for better or worse, avoided in the core).  Generally std::size_t (which is unsigned) is used for array lengths.

**Comment by ofTheo** [comment] 2016-01-26 17:59
huh - I actually don't know why this function is part of ofVec2f.  

To me this is something that belongs in a util class. Its one of the only functions which takes an array of other vec2fs as an argument. 

It also doesn't do anything with the internal data expect set the result of the operation to it. 
I would maybe understand it as a static function that took a vector of ofVec2f's as an argument   i.e.: 

```
ofVec2f avg = ofVec2f::average(myVectorOfVec2fs); 
```

But how it is now with a pointer as the argument and its overall usage just doesn't seem to fit with the rest of OF.

**Comment by ofTheo** [comment] 2016-01-26 18:00
we should fix the issue though - at least kill the bug. 
but maybe it should be marked as deprecated in favor of a different approach?

**Comment by bakercp** [comment] 2016-01-26 18:03
I think the issue is fixed with the PR that was merged.  On a related issue, I think all of these vec classes will be deprecated when we move to glm no?

**Comment by bakercp** [comment] 2016-01-26 18:04
@tpltnt this is fixed now that your PR was merged ... correct?

**Comment by tpltnt** [comment] 2016-01-26 19:27
Yes, my PR fixed the issue.

**Closed** 2016-01-26 19:34 UTC
Labels: bitesize, bug, code-review, core
