### ISSUE TITLE
Cannot add C flags in OF Android Studio project

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#6315] opened 2019-06-24 08:21 UTC
I would like to add C flags in OF Android Studio project.

I tried to add the flag in the `build.gradle` like the following:

```
android {
        // openFrameworks currently only supports compiling against SDK 19
        compileSdkVersion = 25
        buildToolsVersion = "25.0.3"

        defaultConfig.with {
            minSdkVersion.apiLevel    = 19
            targetSdkVersion.apiLevel = 25
            versionCode     =  1
            versionName     = "1.0"


            externalNativeBuild {
                cmake {
                    cFlags "-DLUA_USE_ANDROID"
                }
            }
        }
    }
```
But I get:

> Gradle DSL method not found: 'cFlags()'

How can I correctly add C flags to an Android Studio Project?

---------------------------

Also, setting the `ADDON_CFLAGS` in `addon_config.mk` and creating a project using PG doesn't seem to have any effect. I tried the following but didn't work

```
android/armeabi-v7a:
	ADDON_CFLAGS += -DLUA_USE_ANDROID
```

**Comment by cuinjune** [comment] 2019-06-25 16:17
I think the C flags work after adding the `CFlags.addAll(addonCppFlags(abi, ofRoot()))` in build.gradle file  like the following:

```
 // Setup the different types of flavors (arm / x86),
 // and add linker flags based on that
 android.productFlavors {
        getAbis().each { abi ->
            create(getFlavorName(abi)) {
                ndk {
                    abiFilters.add(abi)

                    cppFlags.addAll(coreCppFlags(abi, ofRoot()))
                    cppFlags.addAll(addonCppFlags(abi, ofRoot()))
                    CFlags.addAll(addonCppFlags(abi, ofRoot())) //This is added

                    ldLibs.addAll(coreLdLibs(abi, ofRoot()))
                    ldLibs.addAll(addonLdLibs(abi, ofRoot()))

                    ldFlags.addAll(coreLdFlags(abi, ofRoot()))
                    ldFlags.addAll(addonLdFlags(abi, ofRoot()))
                }
            }
        }
    }
```
However, the C flags only seem to work when I concatenate the flags one by one.
```
    ADDON_CFLAGS = -DHAVE_UNISTD_H 
    ADDON_CFLAGS += -DUSEAPI_DUMMY
    ADDON_CFLAGS += -DPD
    ADDON_CFLAGS += -DLIBPD_EXTRA
    ADDON_CFLAGS += -DLIBPD_USE_STD_MUTEX
```
If I write the flags as a list, it seems like only the first flag is recognized. (not fully tested though)
`ADDON_CFLAGS = -DHAVE_UNISTD_H -DUSEAPI_DUMMY -DPD -DLIBPD_EXTRA  -DLIBPD_USE_STD_MUTEX`

I hope this can be fixed.

**Comment by danomatika** [comment] 2019-12-10 12:02
This is a duplicate of #6251.

**Comment by arturoc** [comment] 2019-12-10 12:04
going to close it then

**Closed by arturoc** 2019-12-10 12:04 UTC
