### ISSUE TITLE
ofTexture::bind() won't work without ofDisableArbTex() calling

### ISSUE THREAD

**Issue by nama-gatsuo** [openframeworks/openFrameworks#6099] opened 2018-08-04 10:31 UTC
Hello,

As some ppl discussed e.g. [here](https://forum.openframeworks.cc/t/how-to-bind-offbo-texture-to-a-3d-object/27760), `ofTexture::bind()` - `ofTexture::unbind()` are working only with `ofDisableArbTex()` call. 

But I think they should work without `ofDisableArbTex()` (as default). And It would be solved with little modification like below in ofGLProgrammableRenderer.cpp 

* Always check the internal format of texture and if the format is `GL_TEXTURE_RECTANGLE_ARB` then scale the texture coordinates.

```C++
void ofGLProgrammableRenderer::bind(const ofTexture & texture, int location){
	//we could check if it has been allocated - but we don't do that in draw()
	if(texture.getAlphaMask()){
		setAlphaMaskTex(*texture.getAlphaMask());
	}
	enableTextureTarget(texture,location);

	//if(ofGetUsingNormalizedTexCoords()) { <-- **delete this condition**
		matrixMode(OF_MATRIX_TEXTURE);
		pushMatrix();
		glm::mat4 m = glm::mat4(1.0);

//#ifndef TARGET_OPENGLES <-- **delete this condition also**
		if (texture.texData.textureTarget == GL_TEXTURE_RECTANGLE_ARB) {
			// this code will solve this issue
			m = glm::scale(m, glm::vec3(texture.texData.width, texture.texData.height, 1.0f)); 
		} else {
//#endif
			m = glm::scale(m, glm::vec3(texture.texData.width / texture.texData.tex_w, texture.texData.height / texture.texData.tex_h, 1.0f));
		}
		loadMatrix(m);
		matrixMode(OF_MATRIX_MODELVIEW);
	//}
	if(texture.isUsingTextureMatrix()){
		matrixMode(OF_MATRIX_TEXTURE);
		if(!ofGetUsingNormalizedTexCoords()) pushMatrix();
		multMatrix(texture.getTextureMatrix());
		matrixMode(OF_MATRIX_MODELVIEW);
	}
}
```

Stil the code above needs some tests if it does not destroy other rendering-process.
How do you think?

Thanks in advance.

**Comment by arturoc** [comment] 2018-08-04 10:42
Hi, bind and unbind work fine without disabling rectangular textures. the difference is that rectangular textures use texture coordinates expressed in pixels rather than normalized. This is an opengl standard and openframeworks has always used pixel coordinates by default so a change like this would introduce a lot of very hard to debug errors.

In any case this is not a bug so i'm going to close the issue but feel free to keep commenting if you think there should be any other solution to provide normalized coordinates by default

**Closed by arturoc** 2018-08-04 10:42 UTC

**Comment by nama-gatsuo** [comment] 2018-08-04 11:16
I see. thank you for your quick response. I agree with.

If someone like me wants prefereable results in `ofTexture::bind()` without `ofDisableArbTex()`,  it's better to attach new texcoords to ofRectangle() or ofMesh::plane() rather than modify the global renderer.
