### ISSUE TITLE
ofxKinect errors on oF Stable using Visual Studio 2015

### ISSUE THREAD

**Issue by jing1234** [openframeworks/openFrameworks#5503] opened 2017-03-21 15:52 UTC
Hi,
Anybody can help me?
 i try to use ofxkinect addon in vs 2015. But i always meet some errors.

I figured some errors, But there are still 3 errors, which i have no idea.
I use VS 2015, windows 10 and of-0.9.0 and i also tried 0.9.8 but meet the same errors.

```
1>e:\ma\api\of_v0.9.0_vs_release\of_v0.9.0_vs_release\addons\ofxkinect\libs\libfreenect\platform\windows\libusb10emu\libusb-1.0\libusb.h(67): error C4430
1>e:\ma\api\of_v0.9.0_vs_release\of_v0.9.0_vs_release\addons\ofxkinect\libs\libfreenect\platform\windows\libusb10emu\libusb-1.0\libusb.h(67): error C2146: missing “;”(before “libusb_get_device_list”)
```

For this error, I think it too strange. @

```
1>..\..\addons\ofxKinect\libs\libfreenect\platform\windows\libusb10emu\libusb-1.0\libusbemu.cpp(72): fatal error C1083: can not open: “freenect_internal.h”: No such file or directory
For this error i tried to copy the  “freenect_internal.h” to this file or use the path of the “freenect_internal.h”. But it not work, and lead more errors.
```

Thanks and Best Wishes

Jing

**Comment by ShadowMitia** [comment] 2017-04-01 00:00
Did you follow the instructions here? https://github.com/openframeworks/openFrameworks/blob/master/examples/computer_vision/kinectExample/src/ofApp.h

**Comment by bakercp** [comment] 2017-05-22 16:32
@jing1234 did the solution proposed by @ShadowMitia fix your issue?

**Comment by bakercp** [comment] 2017-05-22 16:33
Also @jing1234 Is this solved if you use the nightly VS release?

**Comment by bakercp** [comment] 2017-05-22 16:43
Closing this as a duplicate of #5314

**Closed by bakercp** 2017-05-22 16:43 UTC
Labels: addon, visual studio, waiting-for-feedback
