### ISSUE TITLE
Code completion not working on codeblocks

### ISSUE THREAD

**Issue by pierrep** [openframeworks/openFrameworks#2553] opened 2013-09-11 01:05 UTC
Code completion not set up by default in the OF workspace.

To get autocomplete working again, go to Settings->Editor->Code Completion->C/C++ Parser and select "Use one parser for the whole workspace"

This should then be saved in the OF workspace.

**Comment by AmnonOwed** [comment] 2015-02-02 17:06
This issue still exists in OF 0.8.4. or rather Code::Blocks 13.12. Reproduced on Windows. So the title of this issue may be generalized to "Code completion not working in code::blocks". The workaround still fixes it, but it is a general setting (luckily!). Once toggled, it works for every workspace you open.

The setting is part of a CB plugin. So I wonder if it is even possible to enforce the desired behavior from a workspace file. I do see code completion mentioned in CB's project file [here](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/win_cb/openFrameworksLib.cbp#L509), but nowhere on the web have I found instructions for these settings.

Perhaps it's better to add the manual setting as a tip to the Code::Blocks setup guide?

**Comment by bilderbuchi** [comment] 2015-02-02 20:02
the doc suggestions sounds good. for the first question, it's probably a good idea to enquire with the C::B devs?

**Comment by tjohnman** [comment] 2015-09-04 20:19
This is a Code::Blocks bug. I can confirm it on CB 13.12 on Arch Linux 64 bit.

Any mentions to it in the forums I've seen have been met with hostility, and the source package hasn't been updated in two years.

Have you had any luck enquiring with the devs?

**Comment by fondofcoding** [comment] 2018-02-12 13:09
please fix this bug. It still remains.

**Comment by ofZach** [comment] 2018-02-12 13:38
@fondofcoding we don't support code blocks anymore.   our supported platforms are listed here: 

http://openframeworks.cc/download/

going to close this issue

**Closed by ofZach** 2018-02-12 13:38 UTC
Labels: bitesize, bug, codeblocks , documentation, linux, prelim-analysis

**Comment by shivanand217** [comment] 2018-03-26 04:51
Thanks @pierrep its working.

**Comment by vsbali** [comment] 2018-05-08 18:03
This can be avoided for windows users **by opening code blocks from start menu.**

**Comment by dbc2201** [comment] 2018-11-14 22:46
Hey @pierrep I have the same issue on my codeblocks 16.01 lInux version. I tried the 'Use one parser' fix but it does not seem to work. Is there any other way?

**Comment by dbc2201** [comment] 2018-11-14 22:50
> Hey @pierrep I have the same issue on my codeblocks 16.01 lInux version. I tried the 'Use one parser' fix but it does not seem to work. Is there any other way?

I found a simple hack that seems to work. If we were to open two or more files simultaneously, then the 'parser is still loading files' pop-up does not come up and the code completion works fine.

**Comment by pierrep** [comment] 2018-11-14 23:52
@dbc2201 OF doesn't support Codeblocks anymore. qtCreator is much, much better. I highly recommend you upgrade.

**Comment by dbc2201** [comment] 2018-11-15 06:15
I haven't used qtCreator before. Will give it a try, thanks. The hack I found seems to be working for me for the time being.
