### ISSUE TITLE
ofJoinString produces garble 0.9

### ISSUE THREAD

**Issue by borg** [openframeworks/openFrameworks#4363] opened 2015-09-11 18:18 UTC
oF0.9 commit 9a6bffcaee5e43c274b26ea149e4760d60aa6987
OSX 10.10.3
64bit build

`vector<string> strs;`
    strs.push_back("Bitch");
    strs.push_back("better");
    strs.push_back("have");
    strs.push_back("my");
    strs.push_back("money");
    
    string str = ofJoinString(strs, ",");
    
    cout<<str<<endl;
produces
\255\276\255\336\336\300ݺ\320\

Has usage changed due to introduction of const?

**Comment by raphaelss** [comment] 2015-09-11 18:39
I took a look at the code and I believe the implementation is not correct.
Also, it makes too many unecessary allocations that could be reduced to a single one.
I've been wanting to contribute to oF and this small problem seems like a good place to start.
Would a fix for this be appreciated?

**Comment by jvcleave** [comment] 2015-09-11 18:40
Previous implementation works

```
string resultString = "";
	int numElements = stringElements.size();

	for(int k = 0; k < numElements; k++){
		if( k < numElements-1 ){
			resultString += stringElements[k] + delimiter;
		} else {
			resultString += stringElements[k];
		}
	}

	return resultString;
```

**Comment by borg** [comment] 2015-09-11 18:49
Yeah, the current implementation is not very legible in comparison.
It works on 32bit though. Seems to be a UTF8 issue?!

string ofJoinString(const vector<string>& stringElements, const string & delimiter){
	if(stringElements.empty()){
		return "";
	}
	return std::accumulate(stringElements.cbegin() + 1, stringElements.cend(), stringElements[0],
		[delimiter](std::string a, std::string b) -> const char *{
			return (a + delimiter + b).c_str();
		}
	);
}

**Comment by raphaelss** [comment] 2015-09-11 18:50
This looks correct to me, but with the same problem that multiple memory allocations may be done.

**Comment by raphaelss** [comment] 2015-09-11 19:14
This way we do a single memory allocation:

    string ofJoinString(const vector<string>& stringElements, const string & delimiter){
    	if(stringElements.empty()){
    		return "";
    	}
    	auto numStrings = stringElements.size();
    	string::size_type strSize = delimiter.size() * (numStrings - 1);
    	for (const string &s : stringElements) {
    		strSize += s.size();
    	}
    	string str;
    	str.reserve(strSize);
    	str += stringElements[0];
    	for (decltype(numStrings) i = 1; i < numStrings; ++i) {
    		str += delimiter;
    		str += stringElements[i];
    	}
    	return str;
    }

**Comment by arturoc** [comment] 2015-09-12 01:51
is this the exact code that it's failing for you? i've uploaded some tests for this and other string manipulation functions and they are building fine in both osx and linux. if it's not, can you post a minimal example that is failing or run the tests in your computer? you can run them from `scripts/ci/osx` then run: `./run_tests.sh`

**Comment by jvcleave** [comment] 2015-09-12 02:18
@arturoc when I ran it the only change I did to the original code in the first post was 

`vector<string> strs;` 

It builds fine on Mac but the output is corrupt

**Comment by raphaelss** [comment] 2015-09-12 02:34
The problem is that the lambda function in std::accumulate is returning a pointer to the data inside a temporary object.
std::string::c_str() return a pointer to the data inside a std::string. The thing is that the string built by (a + delimiter + b) is temporary and is gone (and so is its data) by the time the lambda function is called again.
This is undefined behaviour and if you're getting correct results, it's just luck.
To change the minimum necessary for the code to work, make the lambda function return the actual std::string. Making the lambda parameters references would be good too.
But you would still be doing multiple allocations due to high number of appends without preallocating the storage.
I have made a pull request with my version (https://github.com/openframeworks/openFrameworks/pull/4364), but I don't mean to sound pushy.
Feel free to reject it if needed.

**Comment by borg** [comment] 2015-09-12 02:46
Exact code yes (sorry about vector<string> strs;)
Works on 32 but not on 64 bit.
Ran your script @arturoc and all passed.
Thanks for looking in to this @raphaelss Contributions always welcome.

**Closed** 2015-09-12 10:00 UTC
