### ISSUE TITLE
Can’t compile master branch for RPi B+ 

### ISSUE THREAD

**Issue by moebiussurfing** [openframeworks/openFrameworks#4169] opened 2015-07-28 22:13 UTC
I get this errors when compiling an example:

/home/pi/OFgit/openFrameworks/libs/openFrameworks/types/ofTypes.h:286:1: error: expected unqualified-id before 'using'
makefileCommon/compile.core.mk:234: recipe for target '/home/pi/OFgit/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/events/ofEvents.o' failed
make[2]: *** [/home/pi/OFgit/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/obj/Release/libs/openFrameworks/events/ofEvents.o] Error 1
makefileCommon/compile.core.mk:205: recipe for target 'Release' failed
make[1]: *** [Release] Error 2
make[1]: Leaving directory '/home/pi/OFgit/openFrameworks/libs/openFrameworksCompiled/project'
/home/pi/OFgit/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: *** [Release] Error 2

I put the detailed info here:
http://forum.openframeworks.cc/t/cant-compile-master-branch-for-rpi-b/20297

**Comment by bakercp** [comment] 2015-07-28 23:29
See https://github.com/openframeworks/openFrameworks/issues/4146 we need to require GCC 4.8+.

**Comment by bilderbuchi** [comment] 2015-07-29 07:24
closing as duplicate of #4146

**Closed by bilderbuchi** 2015-07-29 07:24 UTC
