### ISSUE TITLE
Support for the Raspberry Pi 2 B

### ISSUE THREAD

**Issue by pizthewiz** [openframeworks/openFrameworks#3620] opened 2015-02-05 01:19 UTC
As reported in the forum thread [Raspberry Pi 2 install failing](http://forum.openframeworks.cc/t/raspberry-pi-2-install-failing), it sounds as though the existing Raspberry Pi support is detected via the cpu type which has gone from ARM11/`ARMv6` in the A/+ and B/+ to Cortex-A7/`ARMv7` with the 2 B.

**Comment by kylemcdonald** [comment] 2015-02-05 01:34
i'm adding this to 0.9.0 under the assumption that it's not a big change, but it's important. if it turns out to be very complicated, or testing compatibility is delaying the release further, we can push it back.

**Comment by bilderbuchi** [comment] 2015-02-05 20:25
pinging @openframeworks/linuxarm who should know how to best fix this.

**Comment by bakercp** [comment] 2015-02-05 20:48
I'm waiting on one as well, so I should be able to give a little better input.  Here's what I'd do:

1.  Copy this file into the linux armv6l folder 

https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk

and call it `config.linuxarmv7l.rpi2.mk`.

2. Then I'd change My remove the `pkg-config` checks so to allow me to figure out what (if any) additional libraries need to be added to the install-dependencies script.

3. Then I'd make obvious changes like changing `armv6l` to `armv7l` [here](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/linuxarmv6l/config.linuxarmv6l.default.mk#L100),

4.  Then I'd try to run it directly on the quad core RPI2 with a command like this:

```
$ export MAKEFLAGS="-j4 -s PLATFORM_VARIANT=rpi2"
$ make
```

**Comment by rc1** [comment] 2015-02-06 14:26
I can confirm this works when the architecture is set to: `armv7-a`.

**Comment by PTS93** [comment] 2015-02-06 14:46
Indeed I can confirm that, when using armv7-a I can successfully compile.

**Comment by bakercp** [comment] 2015-02-06 14:53
Great!  Can one of you submit a PR with the rpi2 configuration variant?  I'll edit my instructions above as well.  So -- in addition to compiling, does it seem to be running OK?

**Comment by arturoc** [comment] 2015-02-06 15:02
probably we don't need a specific variant an instead just detect the platform architecture? that way is easier to maintain if we add libraries... since it seems everything else is compatible

**Comment by bakercp** [comment] 2015-02-06 15:11
@arturoc The only issue there is all of the RPi specific setup stuff that is currently (perhaps incorrectly) handled with `TARGET_RASPBERRY_PI`.  Other ARM7 platforms don't need to define this, which is currently how we avoid x11 and init `dispmanx`, etc etc.  I'm all for auto-detecting all of this stuff, but we just need some way to make sure those defines get set.

**Comment by bakercp** [comment] 2015-02-06 15:12
(also the platform variant strategy is also how we deal with the idiosyncrasies of UDOO, which is armv7).

**Comment by arturoc** [comment] 2015-02-06 15:23
oh i see, i didn't remember that we had different folders for the different architectures and arm6 defaults to rpi. yeah let's add a variant then although in the future it might be good to join linux and linux64 as one thing and linuxarm as another and just detect the architecture since the rest of settings are the same usually

**Comment by rc1** [comment] 2015-02-06 15:30
@bakercp yip all seems to work. Currently I can't test against the latest on github because of [this issue](https://github.com/openframeworks/openFrameworks/issues/3529). 

For the PR do you want just the `config.linuxarmv7l.rpi2.mk` file added? If it's more, I'll need some guidance on what to do / needs doing.

**Comment by bakercp** [comment] 2015-02-06 15:42
@arturoc Yes, it would be super cool if we could merge arm and such in the future and do better detection.  

@rc1 Yes, just a PR including the working `config.linuxarmv7l.rpi2.mk` in the linuxarmv7l directory would be super cool.

That said, I'm going to be working on https://github.com/openframeworks/openFrameworks/issues/3529 over the next day or two, so if the only changes were those I outlined above (and your `armv7-a` fix) then I can just include it with my fix for #3529.

**Comment by PTS93** [comment] 2015-02-06 16:27
So far everything I tried out is working fine. I tried ofxOMXPlayer aswell which is working even better than before.

**Comment by bakercp** [comment] 2015-02-06 17:12
@PTS93 So exciting!  I'll merge.

**Comment by bakercp** [comment] 2015-02-06 23:52
Fixed with6098cf6597134026d9f66ccf52aa693cf46b5ed8

**Closed** 2015-02-06 23:53 UTC
Labels: bug, linuxarm, section-internals
