### ISSUE TITLE
Using ofSoundStream and ofSoundPlayer together on OSX creates terrible noise

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#3851] opened 2015-05-19 02:28 UTC
here is the minimum code to reproduce (on git master)
in ofApp.h
```c++
    ofSoundStream soundStream;
    ofSoundPlayer soundPlayer;
```
in ofApp.cpp
```c++
void ofApp::setup(){
    soundStream.setup(this, 2, 0, 44100, 128, 4);
    soundPlayer.load("iuea-violao2.wav");
    soundPlayer.stop();
}
```

This sequence generates an audio glitch (it was not present until the great update some days ago)
if I comment soundStream.setup line it doesn't happen. 
If I comment soundPlayer.stop() line it doesn't happen too
tested with wav and aif files.
Let me know if you can reproduce it.

**Comment by arturoc** [comment] 2015-05-19 06:14
what platform are you in?

**Comment by dimitre** [comment] 2015-05-19 10:21
OS X 10.10 XCode 6.3

**Comment by admsyn** [comment] 2015-05-19 17:39
I can reproduce this, sounds like an uncleared buffer being looped (different every time). Implementing a buffer-clearing ofApp::audioOut() doesn't fix it.

**Comment by bilderbuchi** [comment] 2015-07-01 08:18
@openframeworks/sound could any of you take a stab at this?

**Comment by admsyn** [comment] 2015-07-01 16:53
> any of you

:p

I've been too busy to get involved the last couple months, but should be able to get back into things in ~a week. I won't be able to tackle this immediately though.

The bug seems very similar to #1694, i.e. a conflict between rtAudio and FMOD. I'd guess one of the libs is configuring some shared resource in the low level OSX audio system in a way that's incompatible with the other. Sounds like a hair-puller, but I'll get to it ASAP (though if anyone else would like to jump in, by all means do! :)

**Comment by bilderbuchi** [comment] 2015-07-01 21:02
> :p

sorry, I only realized after posting. :-P

**Comment by arturoc** [comment] 2015-08-09 11:38
it seems this happened already sometime ago:

https://github.com/openframeworks/openFrameworks/issues/1694

we solved it by rolling back to the previous version of FMOD but i'm not sure which version that was.

**Comment by arturoc** [comment] 2015-08-09 11:40
also changing the buffer size to 1024 in the sound stream fixes the problem as it happened with #1694 so it's surely something that could be fixed by rolling back to the old version of FMOD. FMOD ex is anyway deprecated in all it's versions so it shouldn't be a problem to go back a couple of versions

**Comment by arturoc** [comment] 2015-08-09 12:08
Ok so this won't be fixed. The oldest version which is available in fmod page is 43405 which already has the problem. We were using 42200 but that's not available any more and the binary we were using was 32bit only so it won't work now.

Anyone with this problem should use 1024 as buffer size in the sound stream by now. We'll try to update to the newer fmod studio or to a different api for sound player for next release since fmod ex is outdated now

**Closed by arturoc** 2015-08-09 12:08 UTC
Labels: bug, critical, macOS, prelim-analysis, regression, section-sound

**Comment by ofZach** [comment] 2015-08-09 13:34
I seemed to remember this also related to a header / library mismatch but I could be wrong.  

It might be good to put in a small example with the larger buffer size with some notes so we can point people in the right direction and / or some way of automatically preventing them from creating this ear shattering tone .  I remember this bug hurting really bad when I was out installing somewhere, it's really painful.   Even just a small example like soundPlayerAndSoundStream might be enough to help signal folks in the right direction.

**Comment by i-n-g-o** [comment] 2015-08-09 14:25
a workaround for this is to synchronize the buffersizes of ofSoundStream and ofSoundPlayer.
This PR adds `ofFmodSetBuffersize` to ofFmodSoundPlayer.
https://github.com/openframeworks/openFrameworks/pull/4210

so this one works:
```
soundStream.setup(this, 2, 0, 44100, 128, 4);
	
ofFmodSetBuffersize(128);	
soundPlayer.load("beat.wav");
soundPlayer.stop();
```

**Comment by danoli3** [comment] 2015-11-24 16:16
Also note:
In this order it does not happen except for a small one off sound.
```
        soundPlayer.load("sounds/Violet.mp3");
	soundPlayer.stop();
	
	soundStream.setup(this, 2, 0, 44100, 128, 4);
```
