### ISSUE TITLE
oF Master Windows + Qt 5.7.0 does not draw 

### ISSUE THREAD

**Issue by gfiao** [openframeworks/openFrameworks#5148] opened 2016-07-04 11:02 UTC
I've been using of with Qt, and with the latest version of Qt, 5.7.0, plus the master version of openFrameworks, I am not able to draw anything in the of window, since the window just stays black. I did not have this problem when using of 0.9.3 and Qt 5.5.0.

**Comment by bakercp** [comment] 2017-05-22 21:04
Closing this, as I am not able to reproduce given the lack of information, test code etc and it is not a clear openFrameworks issue.  Please reopen / resubmit with a minimal test case an instructions if the issue persists.

**Closed by bakercp** 2017-05-22 21:04 UTC
