### ISSUE TITLE
don't strip gitignore/.gitignore from script/templates when building releases

### ISSUE THREAD

**Issue by Potato95** [openframeworks/openFrameworks#5792] opened 2017-10-31 20:10 UTC
so i'm getting into using Git with my projects. In the OF book it says that there is a gitignore file in the file path scripts/templates/gitignore/.gitignore. But when i go to that folder there is only a config file?? am i missing something? Cheers!!

**Comment by bakercp** [comment] 2017-10-31 21:31
It's there.  https://github.com/openframeworks/openFrameworks/blob/master/scripts/templates/gitignore/.gitignore

Perhaps, since the file starts with a "dot" (e.g. `.gitignore`) and is therefore considered "hidden" on many file systems you simply can't see it with your current Finder / Explorer / File Browser settings?

**Comment by d-egan** [comment] 2017-12-17 16:11
Hmm, I think this should be reopened.  
It's not a problem if you clone from the repository but "of_v20170714_linux64gcc6_nightly.tar.gz" doesn't have the `.gitignore`
Checked with `ls -a` `ls .*`

**Comment by danzeeeman** [comment] 2017-12-18 14:06
Yeah the releases strip git. This is not a bug.

**Comment by d-egan** [comment] 2017-12-18 14:44
But it's a template `.gitignore` for importing into your own project. right? So it's not used for maintaining the openframeworks repository and should be exempt from the strip.  
Without this `.gitignore`, the gitignore template is useless for everyone who uses the releases.

**Comment by bakercp** [comment] 2017-12-18 14:50
@d-egan I understand you and am reopening this.

This needs to be fixed:

https://github.com/openframeworks/openFrameworks/blob/b8f124f59ac20ae7651fc1ffa64d203362255f96/scripts/dev/create_package.sh#L477

**Comment by bakercp** [comment] 2017-12-18 15:17
I haven't tested it extensively yet, but I just submitted a PR #5824

**Comment by bakercp** [comment] 2017-12-18 16:57
Hi @d-egan I think e got it resolved for future releases. Thanks for your persistence!  Closing this.

**Closed by bakercp** 2017-12-18 16:57 UTC
