### ISSUE TITLE
ofSetVerticalSync does not work correctly, problem identified.

### ISSUE THREAD

**Issue by BananasGoMoo** [openframeworks/openFrameworks#3484] opened 2014-12-15 21:23 UTC
So, I posted an issue before about how ofSetFramerate and ofSetVerticalSync did not work before, and ofSetFramerate was fixed. The issue was closed and I was told to make a new issue when I figured out the problem with vertical sync.

So I am back because I figured out the problem. 

I found that if I get the window pointer (ie: using ofGetWindowPtr()) and then call window->setVerticalSync(true), it works and correctly enables vertical sync. If I instead use the ofSetVerticalSync() function (the one that does not require me to have the window pointer), it does not actually enable vertical sync. So I believe that is the problem with ofVerticalSync actually not setting the vertical sync of the window.

**Comment by NickHardeman** [comment] 2015-10-27 21:45
Is this still an issue? I just tested on OSX 10.8 and ofSetVerticalSync works as expected on the main window.

**Comment by kylemcdonald** [comment] 2015-10-27 22:18
@NickHardeman the original post said that `ofSetVerticalSync()` works but `ofGetWindowPtr()->setVerticalSync(true)` does not.

**Comment by NickHardeman** [comment] 2015-10-28 16:19
I think it's the other way around. But anyways, I tested with both on a single window application and both work as expected. The default being that vertical sync is enabled.
tested using both
`ofSetVerticalSync( false );
ofGetWindowPtr()->setVerticalSync( false );`

**Comment by kylemcdonald** [comment] 2015-10-28 19:40
oh you're right, my bad. closing this since it can't be reproduced :)

**Closed by kylemcdonald** 2015-10-28 19:40 UTC
Labels: bug, core, prelim-analysis
