### ISSUE TITLE
ofAppiOSWindow::Settings not working in current master

### ISSUE THREAD

**Issue by minusplusminus** [openframeworks/openFrameworks#3599] opened 2015-01-30 10:42 UTC
Hello, I've read in the issues list that there are currently some changes in ofAppiOSWindow::Settings.  

      //  here are the most commonly used iOS window settings.
         //------------------------------------------------------
         ofAppiOSWindow::Settings settings;
         settings.enableRetina = true; // enables retina resolution if the device supports it.
         settings.enableDepth = false; // enables depth buffer for 3d drawing.
         settings.enableAntiAliasing = true; // enables anti-aliasing which smooths out graphics on the screen.
         settings.numOfAntiAliasingSamples = 2; // number of samples used for anti-aliasing.
         settings.enableHardwareOrientation = true; // enables native view orientation.
         settings.enableHardwareOrientationAnimation = false; // enables native orientation changes to be animated.
         settings.rendererType = OFXIOS_RENDERER_ES1; // type of renderer to use, ES1, ES2, etc.
    
         ofAppiOSWindow window(settings);
    ofSetupOpenGL(&window, 0, 0, OF_FULLSCREEN);
    
    window.startAppWithDelegate("BleepAppDelegate");

When I change  it to ofiOSWindowSettings, I get an crash on:

     //------------------------------------------
     void ofCoreEvents::notifySetup(){
     	ofNotifyEvent( setup, voidEventArgs );
     }

**Comment by danoli3** [comment] 2015-01-31 03:58
Yeah seems to be an issue in the custom delegate only.

Something deeper with the new windowing code and how it works with custom
delegates.

I did notice this when updating the iOS example main functions.

@julapy any ideas?

**Comment by danoli3** [comment] 2015-02-04 00:15
More information from @tallavi 
> My application is initializing from within a viewController inside a storyboard. I copied the idea from the > iosStoryBoard example.

>Now it seems that the init process is changed. I tracked the unneeded destruction to these lines in >ofxIOSEAGLView.mm:

>if(app != ofGetAppPtr()) {              // check if already running.
>    ofRunApp(shared_ptr<ofBaseApp>(app));    // this fallback only case occurs when app not created in >main().
>}
>The code goes into the if since the app was not created but not ran, and after exiting this line, I get the >destructor because is seems that no one on the inside took that shared_ptr and saved it! I followed the >code inside and I verified that the app is being put in the map that maps windows into apps. I don't >understand why it's getting released! 
>http://forum.openframeworks.cc/t/help-crashing-because-my-app-is-being-destoryed-by->ofxioseaglview/18410/2

**Comment by tallavi** [comment] 2015-02-04 08:46
Thanks for the info, @danoli3. I thought I was losing it.

My temporary work around is to change the lines to:

    shared_ptr<ofBaseApp>* temp = new shared_ptr<ofBaseApp>(app);
    	
    if(app != ofGetAppPtr()) {              // check if already running.
			
        ofRunApp(*temp);   // this fallback only case occurs when app not created in main().
    }

in order to have a app be kept by a pointer that will never get out of scope. I don't care too much for memory leaks at the moment.

As I said, I also tried to understand why the app is being destroyed and I'm missing something, probably something that I don't understand regarding how shared_ptr's actually work. We create the shared_ptr and pass it in, and I verified that it is actually getting inside windowsApps map, so another shared_ptr is created there, pointing to the same address, and when the method returns and the original shared_ptr gets out of scope, the object shouldn't be destroyed but it is! Anyone has a clue regarding why it would do that?

**Comment by danoli3** [comment] 2015-02-04 09:14
@julapy and I have a fix coming up now.

**Comment by tallavi** [comment] 2015-02-04 09:20
Nice!! I did some more investigating, and you might know that already, but I'll write it down just in case it's helpful somehow:

The problem is that the shared_ptr chain starts in the middle, and not at the top. Even if I try to retain my app in a shared_ptr, when I pass it down to ofxIOSViewController, I pass a raw pointer, that gets passed down as raw pointer to ofxiOSEAGLView, and from there to ofRunApp. Inside there, a new chain of shared_ptr's is created, but when it's done (in the piece of code I wrote), the object is destroyed. 

IMHO, the solution should be to convert iOSViewController and EAGLView to work with shared_ptr's also, but:

1) it's breaking compatibility (although, it's very easy to fix).
2) There are places I wasn't sure how to fix, since I needed access to the shared_ptr and all I had was the raw, for example in ofxiOSAppDelegate.

**Comment by tallavi** [comment] 2015-02-04 09:38
Thanks for the quick fix!

WIll you be merging this into your Apothecary/0.9.0-All branch, or should I do merge the new change locally for now?

**Comment by danoli3** [comment] 2015-02-04 10:57
Yeah I've merged julapy's PR into the 0.9.0-All branch now (i'll reset the head when it goes master), for now good to pull

**Comment by minusplusminus** [comment] 2015-02-04 15:25
Enable retina is not working i've mentioned. New issue?

**Comment by bilderbuchi** [comment] 2015-02-05 20:28
fixed by #3617 afaik.
@danoli3 do you know about the retina issue @minusplusminus mentions?

**Closed by bilderbuchi** 2015-02-05 20:28 UTC
Labels: bug, iOS
