### ISSUE TITLE
OF_KEY_COMMAND on OS X 0.9.3, erratic behavior

### ISSUE THREAD

**Issue by dimitre** [openframeworks/openFrameworks#5203] opened 2016-08-16 20:04 UTC
This is a very difficult issue to reproduce, because it works great 99.9% of the time. 
I'm using this shortcut to save some presets everyday and sometimes it returns true even when key is not pressed. I can say this is not a keyboard related issue because I'm observing with different computers. 
Does anybody else have issues with special keys? 
Thank you

**Comment by bakercp** [comment] 2016-08-16 20:11
Sound at all like this?

https://github.com/openframeworks/openFrameworks/issues/652

**Comment by dimitre** [comment] 2016-08-17 00:25
hey @bakercp it sounds like this yes. Should I close this as duplicate or keep, as it is another form of reporting the same issue? Cheers

**Comment by bakercp** [comment] 2016-08-17 01:02
Lets mark this as a duplicate and you can add any additional symptoms there.  I think the problem is pretty clear, it's just a little tricky to solve.

**Comment by bakercp** [comment] 2016-08-17 01:02
Duplicate of #652

**Closed by bakercp** 2016-08-17 01:02 UTC
