### ISSUE TITLE
Xcode Crashes after finishing compiling the last master

### ISSUE THREAD

**Issue by gorkacortazar** [openframeworks/openFrameworks#3943] opened 2015-06-17 10:04 UTC
With a clean version of the master, Xcode 6.3.2 on Yosemite crashes and closes after when compiling and running any ofx application. It happens on all combinations of Debug/Release, 32/64 bits.

The applications compiles, but crashes when starts running. It started to happen in one of the last weeks commits, in my personal development repo I can revert the commits until a point where doesn't happen.

I will pinpoint the exact commit soon.

![screen shot 2015-06-17 at 11 48 13](https://cloud.githubusercontent.com/assets/608719/8204435/ea4f80ac-14e8-11e5-814f-c4e41ffd3ade.png)

**Comment by tgfrerer** [comment] 2015-06-17 10:19
confirmed this running the latest ProjectgeneratorSimple from apps/

**Comment by gorkacortazar** [comment] 2015-06-17 11:16
Does not happen with an empty project, but in multilight example it happens when loading an image; it may be related to the uri discovery or path translation maybe?

**Comment by ofTheo** [comment] 2015-06-17 11:38
I just tried the multiLightExample on 10.9 with Xcode 6.1 and I don't get any crash. 
Could you try building in Debug and run it from Xcode and see if Xcode can catch where it is crashing. 

Could you also post the path you are running OF from on your Hard Drive i.e.: /Users/theo/Documents/OF/

**Comment by arturoc** [comment] 2015-06-17 11:59
@ofTheo what's crashing is xcode itself not the app i think, right?

**Comment by tgfrerer** [comment] 2015-06-17 12:00
yes. xcode 6.3.2 with me. on irc, btw =)

**Comment by gorkacortazar** [comment] 2015-06-17 12:03
@arturoc  yes, xcode closes and the app never runs. But you can run the compiled binary.
@ofTheo , the main difficulty is that Xcode crashes and closes before any breakpoint in the file when you try to debug. The clean ofx resides in:
/Volumes/DataHD/Projects/ofx_090Test/openFrameworks

The problem resides in the URL parsing segment in ofImage.cpp, if I comment the full block, everything runs perfect, in line 176 to 185.

**Comment by gorkacortazar** [comment] 2015-06-17 12:06
More specifically, in ofImage.cpp, line 178, is the one that causes the crash
`uri = network::uri(fileName);`

**Comment by tgfrerer** [comment] 2015-06-17 12:17
Might be a dependency on Poco, and openssl...

Maybe this is related to what prevents me from compiling in XCode 7 beta, where it refuses to compile saying: 
`/Users/tim/dev/of/libs/poco/include/Poco/Crypto/OpenSSLInitializer.h:26:10: 'openssl/crypto.h' file not found`

**Comment by gorkacortazar** [comment] 2015-06-17 12:45
@tgfrerer Correct, I need to go the this commit: ece2a4200bfabbe8e321acddf66dcf1cc12dad9b , before Poco removal, to avoid this behaviour.

Also i just noticed that while the ofx application compile and runs without a problem, it crashes Xcode if you try to attach the debugger.

**Comment by arturoc** [comment] 2015-06-17 13:16
does it crash when compiling in release too? also does this happen when compiling or when running the app?

**Comment by arturoc** [comment] 2015-06-17 13:16
it doesn't happen for me with 6.0.1 btw

**Comment by gorkacortazar** [comment] 2015-06-17 13:21
@arturoc It compiles and build without a problem.

Only when running (or attaching the app to the debugger if i run it manually), xcode crash. If I comment that URL check line in ofImage, it works without a problem, so for sure is related to the boost change; with the poco version of that check, runs without crashing .

**Comment by arturoc** [comment] 2015-06-17 14:09
can you check if the latest commit fixes it?

**Comment by gorkacortazar** [comment] 2015-06-17 14:14
@arturoc Thanks! It works in all Debug/Release 64bits/32bits combinations

**Comment by tgfrerer** [comment] 2015-06-17 14:15
may be related: on windows, i see a non-crashing debug output:

Exception thrown at 0x76044598 in mySketch.exe: Microsoft C++ exception: network::uri_syntax_error at memory location 0x0018FA4C.

**Comment by arturoc** [comment] 2015-06-17 14:21
i don't think it has anything to do, vs stops when an exception is thrown no matter if it's catched, when a uri is can't be parsed it throws an exception but that was the same with poco. you can tell vs not to stop on them but it's pretty annoying that is enabled by default

**Comment by arturoc** [comment] 2015-06-17 14:21
i'm going to close this then

**Comment by bilderbuchi** [comment] 2015-06-17 14:28
> vs stops when an exception is thrown no matter if it's catched
haha what? that's pretty hilarious!

**Comment by tgfrerer** [comment] 2015-06-17 14:29
Oh, i understand. it's not enabled by default, so not that tragic. You can catch it if you specifically set it using `Debug->Exception settings` in the VS menu.

**Comment by danoli3** [comment] 2015-06-25 14:43
@arturoc I believe this is still causing the crashes in iOS Xcode Simulator.

**Comment by arturoc** [comment] 2015-06-25 15:17
can you try removing all references to this library? the only ones are in ofImage.cpp lines 176 and 178 and ofUtls.cpp in the ofLaunchBrowser function, you can comment it entirely. also comment out the includes in both files. then remove the library and it's headers from the system and the xcconfig

if this solves the problem then we are sure that liburi is the culprit and we can swap it with something else or just keep using poco in those 2 places until this is fixed

**Comment by danoli3** [comment] 2015-06-25 15:20
I'll try that now.

**Comment by danoli3** [comment] 2015-06-25 15:33
Yeah no crash when I defined those references in ofUtils and ofImage and removed the URI headers / lib from the project.

Definitely URI causing this Xcode crash. Maybe this is also something we need to report to Apple

**Comment by arturoc** [comment] 2015-06-25 15:56
yes definitely i reported it to the liburi author but they don't want to add workarounds since it's a bug in xcode. my guess is that the backtrace is so big that it overflows some internal buffer xcode is reserving for it which crashes the process.

something else to try is to divide those lines further to see if it fixes the problem but since it only affects a couple of places probably the easiest would be to ifdef osx and ios to keep using poco

**Comment by danoli3** [comment] 2015-06-25 17:14
Just added a PR to fix this with Poco + removal for now.

**Closed** 2015-07-02 11:55 UTC
Labels: bug, critical, prelim-analysis, xcode
