### ISSUE TITLE
App info.plist not constructed properly using VScode on OSX.

### ISSUE THREAD

**Issue by fred-dev** [openframeworks/openFrameworks#8029] opened 2024-06-30 23:22 UTC
When building with VSCode on OSX the info.plist is not properly constructed causing applications built in this way not to launch through the finder. The same application built with XCode properly constructs the info.plist. It seems the variables are not being resolved with VSCode, there are also entries missing (maybe these are not important and are generated by Xcode).

Using the nightly builds (of_v20240528_osx_release) I get this info.plist when building with XCode:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>22G513</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>advanced3dExample</string>
	<key>CFBundleIconFile</key>
	<string>of.icns</string>
	<key>CFBundleIdentifier</key>
	<string>cc.openFrameworks.advanced3dExample</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>advanced3dExample</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string></string>
	<key>DTPlatformName</key>
	<string>macosx</string>
	<key>DTPlatformVersion</key>
	<string>14.2</string>
	<key>DTSDKBuild</key>
	<string>23C53</string>
	<key>DTSDKName</key>
	<string>macosx14.2</string>
	<key>DTXcode</key>
	<string>1520</string>
	<key>DTXcodeBuild</key>
	<string>15C500b</string>
	<key>LSApplicationCategoryType</key>
	<string>public.app-category.games</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.15</string>
	<key>NSCameraUsageDescription</key>
	<string>This app needs to access the camera</string>
	<key>NSHighResolutionCapable</key>
	<string>NO</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app needs to access the microphone</string>
</dict>
</plist>
```

And this when building the same project with VSCode:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>${DEVELOPMENT_LANGUAGE}</string>
	<key>CFBundleExecutable</key>
	<string>${EXECUTABLE_NAME}</string>
	<key>CFBundleIconFile</key>
	<string>${ICON_NAME}</string>
	<key>CFBundleIdentifier</key>
	<string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>${TARGET_NAME}</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleShortVersionString</key>
	<string>${MARKETING_VERSION}</string>
	<key>CFBundleVersion</key>
	<string>${CURRENT_PROJECT_VERSION}</string>
	<key>NSCameraUsageDescription</key>
	<string>This app needs to access the camera</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app needs to access the microphone</string>
	<key>NSHighResolutionCapable</key>
	<string>${HIGH_RESOLUTION_CAPABLE}</string>
</dict>
</plist>
```

**Comment by dimitre** [comment] 2024-07-28 23:49
hello @fred-dev please check if it is fixed on latest. fixed plist entries and icon for me.

**Closed** 2024-07-28 23:48 UTC

**Comment by fred-dev** [comment] 2024-07-29 07:24
Yes, as it is now things work with the default icon - the parameters transfer over correctly to the ino.plist file in the app package. 

However as far as I can tell the only way to use a custom icon with VScode on OSX is to manually copy the file to the resources folder in the app package and manually change the entry in the info.plist. 
Did I miss an easier way to do this for VSCode?

**Comment by dimitre** [comment] 2024-07-30 23:23
Hey @fred-dev no I think this can be improved. ideas are welcome.
I can imagine a specific folder in the project, like if you create a folder called _icon and put any .icns file inside it could be the default icon for the app, or something similar.
like
```
_icon/myproject.icns
_icon/myproject-debug.icns
```

**Comment by fred-dev** [comment] 2024-07-31 00:23
This could work and would be an easy solution, but manually doing this is acceptable for now.

Alternatively, a variable could be added to the build task in the tasks.json that defaults to the default icon. This would make it an editable variable, a solution that works out of the box for anyone who doesn’t want to make changes. This approach seems neater than using the folder method, as it allows you to specify a resource on any path. However, both options require some work.

Considering the effort required - I am loathe to suggest it, but this might be better handled by the project generator. Solving this issue across all platforms and allowing the project generator to accept an optional path to an icon file for all platforms could be great but would add more complexity to the PG.

On a related note, this reminds me of other issues passing specific information to build tasks, post PG that were always simple but not so elegant workarounds. First is needing to manually alter permissions in an info.plist for iOS apps after running the PG - eg adding location permissions every time I run the PG again to add or remove add ons. I am not experienced in this stuff, and this likely an ignorant proposal, but an intermediate generic OF settings file for all platforms could be another option. This file could specify platform-specific tasks like app permissions and custom icons that are then passed to the build system. I guess to make it work it needs to be optional or generated by the PG if it is not there, and not replaced by the PG if it exists. Again more complexity that does not have a high return.

**Comment by dimitre** [comment] 2024-07-31 12:38
Yes, this reminds me one idea: we don't have a reproduceable recipe for buidling an openFrameworks project.
this was well discussed here: https://github.com/openframeworks/projectGenerator/issues/258

I've made a project called ofbuild which I use everyday instead of projectGenerator GUI
https://github.com/dimitre/ofbuild
each project has a configuration file ```of.yml``` with all addons, additional source folders and you can rebuild everything just typing ```ofbuild``` in your project folder.

addons.make couldn't function as a repetitive recipe because PG actually overwrites it, and it removes any addon not present in addons folder
