### ISSUE TITLE
ofVideoPlayer always starts playing, even when calling stop after loading.

### ISSUE THREAD

**Issue by Hperigo** [openframeworks/openFrameworks#6522] opened 2020-01-17 19:18 UTC
calling `stop` right after loading the movie doesn't have any effect, same after `loadAsync`

```
#include "ofApp.h"
ofVideoPlayer mPlayer;

//--------------------------------------------------------------
void ofApp::dragEvent(ofDragInfo dragInfo){
    mPlayer.loadAsync( dragInfo.files[0] );
    mPlayer.stop(); // <-- this doesn't do anything
}

//--------------------------------------------------------------
void ofApp::setup(){

}

//--------------------------------------------------------------
void ofApp::update(){
    
    if( mPlayer.isLoaded() )
        mPlayer.update();
}

//--------------------------------------------------------------
void ofApp::draw(){
    
    
    
    if( mPlayer.isLoaded() ){
        mPlayer.draw(0,0);
    }
}
```

**Comment by dimitre** [comment] 2020-01-25 17:36
I've noticed ofVideoPlayer starts playing too, but when using Gstreamer it doesn't.

**Comment by ofTheo** [comment] 2020-01-28 17:58
Definitely seems like a bug. 
I think this is due to how macOS loads videos - the video isn't immediately available, so the commands might not be available.  Will look into this for 0.11.1 

Thanks!

**Comment by Hperigo** [comment] 2020-01-28 18:08
Thanks, I did a bit of looking around and it seems that this [line](https://github.com/openframeworks/openFrameworks/blob/1afca9f5925ffd0484405bd015181fa8b02bfa09/libs/openFrameworks/video/ofAVFoundationVideoPlayer.m#L781) is triggering the play:
`bPlaying = (rate != 0);`  in `ofAVFoundationVideoPlayer.m`

**Comment by fred-dev** [comment] 2020-02-16 15:45
@Hperigo did you actually find a fix for this?

**Comment by Hperigo** [comment] 2020-02-17 13:34
hi @fred-dev, not really =/

**Comment by ofTheo** [comment] 2020-02-19 04:04
@Hperigo I think this might be a fix. 

Let me know if it works for you. 

Change these lines: 
https://github.com/openframeworks/openFrameworks/blob/patch-release/libs/openFrameworks/video/ofAVFoundationVideoPlayer.m 

to: 
```
	// auto-play or play if started before beeing ready
	if(bAutoPlayOnLoad || bPlayStateBeforeLoad) {
		[self play];
	}else{
		[self pause];
	}
```

For me calling ofVideoPlayer::stop or not calling ofVideoPlayer::play after ofVideoPlayer::load now results in the movie stopped instead of being auto played.

**Comment by ofTheo** [comment] 2021-01-26 21:55
ha - was trying to reproduce this but its already fixed. 
closing! :)

**Closed by ofTheo** 2021-01-26 21:55 UTC
