### ISSUE TITLE
screen flicker on app launch

### ISSUE THREAD

**Issue by julapy** [openframeworks/openFrameworks#4229] opened 2015-08-11 05:08 UTC
have only see this on osx,
doesn't seem to be happening on ios.

when launching an app, the screen is black for (one or more) frame and then changes to the default background color. when setting `ofBackground(ofColor::red);` in `setup` or `draw`, it shows the same behaviour where the app launches with a black screen and then changes to red.

**Comment by kylemcdonald** [comment] 2015-08-11 10:26
i can confirm, it started happening around the multiwindow merge i think.

it's not a huge deal, but could make the difference in some performance contexts, or when someone is trying to make something end-user facing with OF.

**Comment by ofTheo** [comment] 2015-08-11 11:48
Ah yes. I've seen this issue with glfw. I think I have a fix. 
Could you tag this for 0.9?

**Comment by ofTheo** [comment] 2015-08-11 12:13
hmm actually I am not seeing this with the RC1 - is there code that can reproduce the issue your having. 
Is it only apps which have a slow setup function?

**Comment by julapy** [comment] 2015-08-11 13:02
ive been seeing the issue while working with the latest master and running an app which was empty apart from the code i posted.

might be osx version related, im on 10.10

**Comment by ofTheo** [comment] 2015-08-11 14:22
Ahh - I'm on 10.9.5 - going to check on a 10.10 machine.

**Comment by ofTheo** [comment] 2015-08-11 14:46
Okay I see the issue in master but not in RC1 - so whatever happened to cause it was after the RC1 on August 10th.

**Comment by ofTheo** [comment] 2015-08-11 16:18
okay 0.9.0 RC1 actually is not up to date. its somehow super old.  ( ping @arturoc ) 
looking at the nightly from Sunday which was more up to date it I see the issue there too.   so it could have been around for a while.

**Comment by arturoc** [comment] 2015-08-11 16:32
why do you think is super old? it's generated by the same script that the nightlies so it's weird that it would be different

**Comment by arturoc** [comment] 2015-08-11 16:35
oh, actually the script is generating from stable so RC1 is 0.8.4 pfff

**Comment by ofTheo** [comment] 2015-08-11 16:45
oh - that makes sense. I just shot an email out on the dev list about that so people didn't start testing RC1 too hard :) - be funny to see all the same bugs get re-reported.

**Comment by arturoc** [comment] 2015-08-11 16:58
:)

**Comment by ofTheo** [comment] 2015-08-11 17:21
Okay I think this issue comes from a change in GLFW as I remember seeing it in our project when we started using the GLFW branch we've been manually maintaining. 

I think the issue is that there is a delay between when GLFW creates the window and when you can draw to it and during that time you will see a black window. 

Calling glClear() at the end ofApp::setup or at the beginning of ofApp::draw does not do anything so I don't think its an issue with the OF renderer. 

A partial fix for this issue which we did for our project is to hide the window when its first created and then show it on the first frame. 
ie: 
```
//--------------------------------------------
void ofAppGLFWWindow::update(){
	if( ofGetFrameNum() == 1 ){
		glfwShowWindow(windowP);
	}
	events().notifyUpdate();
}
```

This is not so ideal as there will be a frame where the window will be hidden. 
@arturoc - do you see this in linux?  A good test if the polygonExample

**Comment by ofTheo** [comment] 2015-08-11 17:26
actually this seems to work fairly well. 

add to line 221 (above  `glfwSetWindowUserPointer(windowP,this);` ) 
```
	glfwHideWindow(windowP);
```

then add this to update. 
//--------------------------------------------
void ofAppGLFWWindow::update(){
    if( ofGetFrameNum() == 0 ){
        glfwShowWindow(windowP);
    }
    events().notifyUpdate();
}

@julapy @kylemcdonald  - could you see if that fixes it for you?

**Comment by arturoc** [comment] 2015-08-11 17:37
in linux the window is hidden on creation because otherwise the icon won't be set properly so that could be fixing it but this seems very platform specific. all the code in glfw is mostly different per platform.

anyway we are already hidding the window in linux so it probably only requires removing a couple of ifdef's

**Comment by ofTheo** [comment] 2015-08-11 21:44
huh - I don't see a glfwHideWindow call in ofAppGLFWWindow - all I see is: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L207

On linux is the window hidden by default?

**Comment by arturoc** [comment] 2015-08-11 21:56
oh it's actually hidden at the beginning in every platform: https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/app/ofAppGLFWWindow.cpp#L143

**Comment by ofTheo** [comment] 2015-08-11 22:03
ahh - would it be bad to move the glfwShowWindow to the first update call?  
It would pretty much solve this issue - but not sure what new issues it might introduce. 

for what its worth - we've used this approach on a major project and not had any negative side effects.

**Comment by arturoc** [comment] 2015-08-11 22:06
i think it should be ok

**Comment by ofTheo** [comment] 2015-08-12 14:56
okay I made a PR for this at #4232 
I also added hide window just before the window is closed as there was a similar black flicker when the window was closed which this fixed. 

I'll merge this in a bit if there aren't any objections.

**Closed** 2015-08-12 17:53 UTC
Labels: macOS, regression, section-2D
