### ISSUE TITLE
projectGenerator on linux ( 0.9.0 nightly build )

### ISSUE THREAD

**Issue by nbriz** [openframeworks/openFrameworks#4434] opened 2015-10-14 17:52 UTC
just downloaded the nightly build for linux ( of_v20151014_linux64_nightly.tar.gz ) && ran the new projectGenerator but it looks like i'm missing the command line app, getting this error:

    Command failed: /bin/sh -c projectGenerator  -o"/home/nbriz/openFrameworks/of_v0.9.0_nightly_linux64_release" -a" " -p"linux64" /home/nbriz/openFrameworks/of_v0.9.0_nightly_linux64_release/apps/myApps/mySketch
    /bin/sh: 1: projectGenerator: not found

also, in apps/ there's a directory called projectGenerator/commandLine ( which i tried to complie but failed ) ...not sure if that's meant to be there.

ping: @bakercp

**Comment by ofZach** [comment] 2015-10-14 17:54
I think the nightly might be broken for linux for last night?  @arturoc told me that he fixed something this morning (I checked in a change late yesterday)...

happy to help if you have issues compiling or running the command line tool.

**Comment by nbriz** [comment] 2015-10-14 18:14
thnx @ofZach i'm ok without the projectGenerator, just wanted to make a note of the issue here :)

**Comment by ofZach** [comment] 2015-10-14 18:15
thanks!  much appreciated.

**Comment by arturoc** [comment] 2015-10-14 19:15
have you runned the compilePG.sh script in scripts/linux? the project generator is not compiled for linux in the servers since it won't be compatible with every posible distributiopn so there's this script that compiles it and puts it in the right place

**Comment by nbriz** [comment] 2015-10-14 19:46
i hadn't seen that script ( there's a projectGenerator-linux64/ directory with an app which is what i tried ) i just ran compilePG.sh but got the following error:

    /home/nbriz/openFrameworks/of_v0.9.0_nightly_linux64_release/apps/projectGenerator/commandLine/src/main.cpp:15:28: fatal error: CBLinuxProject.h: No such file or directory
     #include "CBLinuxProject.h"
                            ^
    compilation terminated.
    make[1]: *** [obj/linux64/Release/src/main.o] Error 1
    make[1]: Leaving directory `/home/nbriz/openFrameworks/of_v0.9.0_nightly_linux64_release/apps/projectGenerator/commandLine'
    make: *** [Release] Error 2
    make: Leaving directory `/home/nbriz/openFrameworks/of_v0.9.0_nightly_linux64_release/apps/projectGenerator/commandLine'
    there has been a problem compiling the command line projectGenerator
     please report this problem in the forums

but the file does exist here /addons/ofxPG/libs/ofxPG/include/ofx/PG/CBLinuxProject.h

**Comment by arturoc** [comment] 2015-10-15 07:12
there was actually a problem with the packaging script failing to keep the addon in the folder, todays nightlies have failed because of something else anyway but the issue is fixed now. thanks!

**Closed** 2015-10-15 07:11 UTC

**Comment by nbriz** [comment] 2015-10-15 14:28
great thnx @arturoc + @ofZach

**Comment by buxh012** [comment] 2018-08-12 05:31
in ubuntu 14.04 I try to install the project generator 
I run 
cd  /opt/openFrameworks/scripts/linux
./compilePG.sh
but it doesn't work,geting this error:

make[1]: *** [bin/projectGenerator] Error 1
make[1]: Leaving directory `/opt/openFrameworks/apps/projectGenerator/commandLine'
make: *** [Release] Error 2
make: Leaving directory `/opt/openFrameworks/apps/projectGenerator/commandLine'
There has been a problem compiling the command line projectGenerator.
Please report this problem in the forums.
