### ISSUE TITLE
retina fullscreen is not full

### ISSUE THREAD

**Issue by piem** [openframeworks/openFrameworks#4645] opened 2015-12-04 11:37 UTC
hi!

When starting a fullscreen application on an iPad mini 2, I get black margins:

![ofios_notfull](https://cloud.githubusercontent.com/assets/142960/11588827/a8ac27f6-9a83-11e5-86c0-8cfbca3a1829.jpg)

how can I get rid of them?

cheers, piem

**Comment by julapy** [comment] 2015-12-04 12:07
hi @piem, this sort of usability question is better answered on the OF forum.
github issue logging is for bugs.

but while we are here,
i think the problem is probably caused by building for an iphone device while running on the ipad.
you'll probably need to make the app universal (i think)

please post on OF forum and you should get some more answers there.

closing this issue.

**Closed by julapy** 2015-12-04 12:07 UTC

**Comment by piem** [comment] 2015-12-04 12:32
Ok, sorry for the noise and thanks for the info @julapy, that did the trick.

Just for the record, I had to change the following 2 settings in an XCode project recently created using projectGenerator-ios:

 - General / Deployment Info / Devices: iPhone -> Universal
 - Build Settings / Architectures / Build Active Architecture Only: No -> Yes

Cheers, piem
