### ISSUE TITLE
No webcam image capture on Mojave 

### ISSUE THREAD

**Issue by fabiankraxenberger** [openframeworks/openFrameworks#6518] opened 2020-01-12 13:59 UTC
Code: episode 012 - webcam @lewislepton (simple webcam input) 
https://github.com/lewislepton/openFrameworksTutorialSeries

Mojave: 10.14.6 
XCode: 11.3

Hi out there, I´m quite new to OF. So sorry if this problem is already documented. 

It´s seem like, i have a problem to capture the image of my Webcam. 
I already checked that "plist" permission problems.
 And i also tried to run it outside from Xcode. But i still don´t get a image. 

Any ideas? 

<img width="321" alt="Bildschirmfoto 2020-01-12 um 14 53 59" src="https://user-images.githubusercontent.com/51359986/72219901-70d44400-354b-11ea-9fc9-1826b4ded08b.png">

Warning: 
[BlankFrameRenderer] Releasing cached CVPixelBuffer! This probably shouldn't be happening (except during deallocation)!!

**Comment by roymacdonald** [comment] 2020-01-14 00:09
Hi, did you try one of the example at `examples/video/videoGrabberExample`?
One thing that mojave does is that it asks for permission to use the webcam each time you run the app, unless you "white list" it in the systempreferences.
Which "plist" modification you added?
I am on the same config as you and have no problems using my webcam

**Comment by ofTheo** [comment] 2020-01-14 23:25
I think this could be an issue in 0.10.1 and older with 10.14. 
I believe this is fixed in 0.11.0. 

If you are still having the issue make sure in this panel in your control panel no OF apps are unchecked for the camera privacy settings. 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/144000/72391445-f853bb80-36e1-11ea-912c-5d19a28a2c1d.png">

**Comment by ofTheo** [comment] 2020-01-14 23:26
if this is still an issue in 0.11.0 I can reopen, but I have 10.14 and can't reproduce it.

**Closed by ofTheo** 2020-01-14 23:25 UTC

**Comment by fabiankraxenberger** [comment] 2020-01-16 12:30
Thanks! 
It was my fault, i did not set the Device ID.
