### ISSUE TITLE
ofSetOrientation() makes drawings invisible after ofFbo.begin()/end() on iOS

### ISSUE THREAD

**Issue by cuinjune** [openframeworks/openFrameworks#5872] opened 2018-02-06 06:45 UTC
Hi, I'm using OF v0.9.8 for iOS and I just found out calling `ofSetOrientation()`  makes all drawings invisible after `ofFbo.begin()` and `ofFbo.end()` is called.

Here's a simple test code.
In ofApp.h

    ofFbo fbo;

In ofApp.mm

    //--------------------------------------------------------------
    void ofApp::setup(){
        
        //ofSetOrientation(OF_ORIENTATION_90_RIGHT); //try uncommenting this
        
        fbo.allocate(200, 200, GL_RGBA);
        fbo.begin();
        ofClear(255, 255, 255);
        fbo.end();
    }

    //--------------------------------------------------------------
    void ofApp::update(){
        
    }

    //--------------------------------------------------------------
    void ofApp::draw(){
        
        fbo.begin();
        fbo.end();
        
        ofSetColor(255,0,0);
        ofDrawCircle(ofGetWidth()/2, ofGetHeight()/2, ofGetHeight()/4);
    }

If you run the code, you will see a red circle in the center.
However, if you change the orientation (you can uncomment `ofSetOrientation()` in the `setup()`), the red circle will no longer be visible.

It looks like changing the orientation affects drawings after writing to the FBO.

I tried the same code using the nightly and it didn't have this problem. 
**(EDIT: I made a mistake and it does have this problem in the nightly too)**

Does anyone have any idea what would be the cause of this bug?
Thank you so much.

**Comment by arturoc** [comment] 2018-02-06 14:32
I'm going to close this since it's really not a bug (it's fixed already in master). Here's a link to the forum post explaining the same problem in case someone has an idea of what might be going on: https://forum.openframeworks.cc/t/ofsetorientation-makes-drawing-invisible-after-offbo-begin-end/28731

**Comment by cuinjune** [comment] 2018-02-06 15:48
Hi @arturo
I'm sorry I just realized that I made a mistake when testing the code in 0.10.0 nightly. (I didn't copy `ofSetOrientation()` which I originally had it in `touchDown()` and thought it works in the nightly)
So running the code in the nightly also have this problem. I just double checked it with the newly downloaded nightly build. Could you please reopen this issue?

**Comment by arturoc** [comment] 2018-02-06 15:52
@ofTheo perhaps you can take a look at this?

**Comment by ofTheo** [comment] 2018-02-07 23:02
yup - will look into this! 
I think it might be to do with hardware orientation.

**Comment by ofTheo** [comment] 2018-02-09 15:28
Can confirm the bug. 
Its really strange. Happens on both ES1 and ES2. 

Putting 
`ofSetOrientation(OF_ORIENTATION_90_RIGHT);`
After 
`fbo.end();`

In draw restores the drawing. 

Weirdly putting `ofSetOrientation(OF_ORIENTATION_90_RIGHT);` at the end of `ofGLRenderer::end(const ofFbo & fbo){`
doesn't restore it, but putting it at the end of `void ofFbo::end()` does. 

I thought at some point the matrixStack orientation was not getting restored, but it shows 4 which is 90_RIGHT. 

Going to dig in some more. Just wanted to update.

**Comment by ofTheo** [comment] 2018-04-05 17:41
Okay - the orientation issue now doesn't seem related.  Something since I last checked means it happens regardless of ofSetOrientation calls. 

All you need to do now to kill the screen on iOS is create and try and clear an FBO in ofApp::setup 

Put this in ofApp::setup on iOS 
```
    fbo.allocate(200, 200, GL_RGBA);
    fbo.begin();
    ofClear(255, 255, 255);
    fbo.end();
```

My guess is that because the rendering / render surfaced isn't fully setup somehow at the time ofApp::setup is called - when Fbo::end is called it doesn't correctly restore the matrix / surface etc to the correct setting. 

Moving iOS's setup call to the first time it renders fixes it - but causes other issues. 

Changing this line: 
https://github.com/openframeworks/openFrameworks/blob/master/addons/ofxiOS/src/core/ofxiOSEAGLView.mm#L106

to:
```
    window->renderer()->startRender();
	window->events().notifySetup();
    window->renderer()->finishRender();
```

Fixes the issue. 

I am going to put a PR in with this fix, so others can test. 
There may be a more elegant fix though. 

Pinging @danoli3

**Closed** 2018-04-05 20:48 UTC
