### ISSUE TITLE
CMakefile

### ISSUE THREAD

**Issue by csverma610** [openframeworks/openFrameworks#6441] opened 2019-11-11 22:30 UTC
Hello,

I was able to compile the code. but do  not know how to install it and use the examples.

Is there a CMakefile for the entire project?

**Comment by sourya-sen** [comment] 2019-11-12 04:48
Please see specific instructions for each platform here: https://openframeworks.cc/download/

Otherwise, if you're installing/building from Github, instructions are in the repo. 

CMake is not required for openFrameworks, rather use Project Generator to update examples and compile using `make` and/or XCode/Visual Studio/QtCreator/... depending on your platform and preferences.

**Comment by arturoc** [comment] 2019-11-12 11:01
going to close this since it's a question not a bug report or a feature request. please ask in the forum, if you have further doubts

**Closed by arturoc** 2019-11-12 11:01 UTC
