### ISSUE TITLE
Error with Polyline.getTangentAtIndex()

### ISSUE THREAD

**Issue by peripecio** [openframeworks/openFrameworks#5451] opened 2017-02-15 22:01 UTC
Hi!

I've observed that when you get the tangents (or normals) from the vertices of a polyline with the getTangentAtIndex() method, it returns a wrong result when the vertex is one of those corresponding to the originals points.

I link an extended comment with more details that I've opened in the openframeworks forum.

[https://forum.openframeworks.cc/t/problem-or-error-with-polyline-gettagentatindex/25864]

**Comment by peripecio** [comment] 2017-02-15 22:02
[https://forum.openframeworks.cc/t/problem-or-error-with-polyline-gettagentatindex/25864](https://forum.openframeworks.cc/t/problem-or-error-with-polyline-gettagentatindex/25864)

**Comment by arturoc** [comment] 2017-02-15 22:16
ping @kylemcdonald

**Comment by kylemcdonald** [comment] 2017-03-02 21:34
hmm not sure why i'm noted here. i helped out with the simplification stuff initially, but the tangent code is from @memo... and afaict, none of the current ofPolyline code blames me ;)

**Comment by memo** [comment] 2017-03-03 00:12
wow this is a blast from the past :) yea I wrote the original polyline stuff with normals and interpolation etc. though that was years ago. Looking at the source now I don't recognise much of it :), in fact the cpp is gone altogether! (good move making it templated). but also with the new glm stuff it's quite different to how it was when I wrote it. Looks like @tgfrerer wrote the new bits - at least calcdata, where the tangent is calculated, and just looking at those few lines of code it looks ok. Though I don't understand what `bool noSegmentHasZeroLength = (v1 == v1 && v2 == v2)` means?

**Comment by tgfrerer** [comment] 2017-03-03 10:41
I'm looking into this, and findig it difficult to reproduce - @peripecio, I'm not sure how you are drawing the graph which you attached on the oF forum (seeing the drawing code will help) - could you post a gist that produces these drawings? I'd be mostly interested in the `update()` and `draw()` methods of the app.

@memo yes, these parts I rewrote to fix a regression that came in with using glm, the related isssue (with test gist app) is #5289.

Re: `noSegmentHasZeroLength = (v1 == v1 && v2 == v2);`

There's a comment above that line which explains what it does because it's an unusual operation:

    // If just one of p1, p2, or p3 was identical, further calculations 
    // are (almost literally) pointless, as v1 or v2 will then contain 
    // NaN values instead of floats.

The line protects against an edge case where a segment (either the previous or the following segment) may have zero-length. 

Comparing a float against itself returns `false` in boolean context if the float happens to be `NaN`, which is what we need to protect against here.

**Comment by arturoc** [comment] 2017-03-03 10:49
sorry @kylemcdonald i didn't even checked git blame and thought it was you who had written most of this functions

**Comment by tgfrerer** [comment] 2017-03-09 18:37
@peripecio i wonder, have you been able to isolate / reproduce the issue? If not, I'd suggest closing this thread by next week as "cannot-reproduce"...

**Comment by tgfrerer** [comment] 2017-03-20 11:39
closing this now. @peripecio feel free to re-open if the issue still persists / is reproduceable.

**Closed by tgfrerer** 2017-03-20 11:39 UTC
