### ISSUE TITLE
Feature : VS2015 x64 libs for 0.9.0 release

### ISSUE THREAD

**Issue by elliotwoods** [openframeworks/openFrameworks#3843] opened 2015-05-18 01:35 UTC
Bringing in:

- @LeoColomb
- @DomAmato
- @liquidzym
- @prisonerjohn 

Todo:

- [ ] Build all libs for VS2015 x64 using repos pointed to by current apothecary scripts
- [ ] Test Project Generator
- [ ] Test addons (e.g. OpenCV)

**Comment by DomAmato** [comment] 2015-05-18 03:20
To break out the scripts a bit:

- [ ] cairo
- [ ] fmodex
- [ ] freeImage
- [ ] freetype
- [ ] glew
- [ ] glfw
- [ ] kiss
- [ ] openssl
- [ ] poco
- [ ] portaudio
- [ ] rtAudio
- [ ] tess
- [ ] videoInput

**Comment by DomAmato** [comment] 2015-05-18 04:37
Same for the Addons:

- [ ] ofx3DModelLoader
- [ ] ofxAccelerometer
- [ ] ofxAssimpModelLoader
- [ ] ofxEmscripten
- [ ] ofxGui
- [ ] ofxKinect
- [ ] ofxMultiTouch
- [ ] ofxNetwork
- [ ] ofxOpenCV
- [ ] ofxOsc
- [ ] ofxSvg
- [ ] ofxThreadedImageLoader
- [ ] ofxVectorGraphics
- [ ] ofxXmlSettings

**Comment by elliotwoods** [comment] 2015-05-18 07:10
```
$ ./apothecary -t vs download core addons

 Downloading "FreeImage"

... skipping, src dir already exists

 Downloading "android_configure"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   416    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   385    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 18 2762k   18  503k    0     0  99937      0  0:00:28  0:00:05  0:00:23  119k
 Received signal SIGINT
```

Seems like can't just download all right? will start going through them

**Comment by DomAmato** [comment] 2015-05-18 07:20
is there a reason not to upgrade to glew 1.12? it also builds fine though I think apothecary builds it as Win32

**Comment by elliotwoods** [comment] 2015-05-18 07:33
still trying to spend some time on this today but haven't been able to so far.

let's stick to same versions as osx / other platforms. if they're on 1.12 then let's use that also

**Comment by DomAmato** [comment] 2015-05-18 07:34
I think they are still on 1.11 though don't quote me on that

**Comment by DomAmato** [comment] 2015-05-18 08:26
for GLEW the script needs to change to

      vs-build "glew_static.vcxproj" Build "Release|x64"

but apothecary also doesn't handle architecture switching for compiling with VS so in apothecary line 789 needs to change to:

      cmd.exe /c 'call "%VS'${VS_VER}'0COMNTOOLS%vsvars32.bat" && '$VS_BUILD_TOOL' '$1' /'${2:-Build}' "'${3:-Release}'"'

Also updating VS_VER to 14 on line 79

**Comment by ofTheo** [comment] 2015-05-18 10:51
agreed - libs should be the same versions as in the scripts. 
for addons the only ones that matter are OpenCV and ofxAssimpModelLoader as there the only ones with static libs. 

@elliotwoods the download core addons also didn't work for me. 
I ended up doing each one individually. 

eg: 
./apothecary -t vs download FreeImage

**Comment by LeoColomb** [comment] 2015-05-18 18:29
I think POCO should be the most problematic.
It currently doesn't have any VS2015 project to build, and its CMake structure is bugged (as I remember).
(See a short discussion about CMake implementation with the major POCO contributor, very old but seems to remain relevant: https://github.com/pocoproject/poco/commit/4297d78621d8192339bf78d0e6b5dde189141063#commitcomment-4800811 /!\ **big** commit)

**Comment by LeoColomb** [comment] 2015-05-18 18:37
Ping @stammen and @MSOpenTech from https://github.com/MSOpenTech/openFrameworks/issues/21.
May be some advice for libraries' compilations?

**Comment by bilderbuchi** [comment] 2015-05-18 19:17
in light of the poco information, please keep any work on this separate from the master branch until complete, so that we don't end up with any half-finished but broken components which could delay 0.9.0 even more.

**Comment by DomAmato** [comment] 2015-05-18 23:37
What command line programs do you guys use? I am using git for windows and am getting an error with cairo where the tar command isnt finding the file, though its there

    tar (child): xz: cannot exec: no such file or directory

**Comment by DomAmato** [comment] 2015-05-18 23:57
I think free image needs to be the newer version. Does 3.16 have an x64 build? there arent any pre compiled binaries: http://sourceforge.net/projects/freeimage/files/Binary%20Distribution/3.16.0/
I know 3.17 has both architectures. 

For the time being I am separating things into Win32 and x64 folders so that files dont overwrite each other

**Comment by DomAmato** [comment] 2015-05-19 00:12
Free type upgrades and compiles fine in x64 and msvc 140 if I do it in visual studio using the vs2010 project. Ill try to do it by script but good to know its possible

**Comment by danoli3** [comment] 2015-05-19 00:17
Id be happy to fix up the Apothecary scripts for OS X / iOS for FreeImage to support FreeImage 3.17.0.

I had some custom fixes for it for Xcode and iOS / OS X which I submitted fixes for in August last year, they may be featured in the new build. Else I can repatch it with those changes.

Always best to stay up to date (especially since this is the first patch for FreeImage in a year)

Also if this solves the issues for the Windows builds then all the more need.

**Comment by DomAmato** [comment] 2015-05-19 00:45
GLFW is a little wonky, it builds fine in vs2015 but I think the cmake script needs to be upgraded to support x64. Opening the project in vs2015 and configuring to build for x64 works fine.
 @ofTheo you would be the person to ask about this I assume.

**Comment by DomAmato** [comment] 2015-05-19 00:55
KISS doesn't need to be built for vs?

**Comment by falcon4ever** [comment] 2015-05-19 02:27
I think KISS is just build from the few C source code files (on platforms other than Linux/Linux ARM).

**Comment by arturoc** [comment] 2015-05-19 06:13
KISS is only used in linux to do the fft analisys on the sound player, other platforms use fmod so no need to compile it for vs

**Comment by DomAmato** [comment] 2015-05-19 08:16
@danoli3 what about scripts for rtAudio? Newer versions support WASAPI and would be nice to have since I have actually run into issues where I had to recompile the rtAudio libraries. http://forum.openframeworks.cc/t/rtaudio-problems-in-win-8-1-in-of-0-8-0-fixed/14836/4

**Comment by DomAmato** [comment] 2015-05-19 10:27
@LeoColomb is the cmake bugged? Everything compiled ok for me in both architectures

**Comment by arturoc** [comment] 2015-05-19 10:53
we need to use the same versions as the rest of the platforms since the include files have to be the same. if some library has newer versions which are significantly better or easier to build we can check it it's ok to change them in the rest of the platforms but we need to have all of them in sync.

that said rtaudio is usually really easy to build and the only other platform where we need to build it is in osx so it should be ok, just make sure to have the same version in both osx and windows.

for other libraries more platforms might need libs so be careful to not switch versions without agreeing with other platform maintainers first

**Comment by DomAmato** [comment] 2015-05-19 11:07
right though rtaudio also doesnt build for vs2013/15 unless the code from their github is used. I guess the fix isn't a part of the download from the main site yet though the fix is several months old now. 

https://github.com/thestk/rtaudio/issues/21

**Comment by DomAmato** [comment] 2015-05-19 22:38
Most of the libs have upgraded and compiled without issue. Cairo is being a bit problematic as i get an error when trying to unpack the tar.xz file. Manually unpacking things works but then the prepare function throws errors saying lib src dir pkg-config is missing. Perhaps these are issues with the git for windows bash? OpenSSL is also the next step. Currently the git bash doesn't handle comparing hashfiles but you can do it from command line in windows natively by running 

    cmd.exe /c 'call 'CertUtil' '-hashfile' '$FILENAME.tar.gz' 'SHA1''

though im not immediately sure how to get the output and then compare it against the downloaded SHA file but thats probably doable from the certUtil command as well. Either way I'll start work on the addons tonight probably.

**Comment by elliotwoods** [comment] 2015-05-23 10:20
Sounds like you've got some good momentum with the core @DomAmato 
I'm going to have a look at the 2 addons now, and head over to join you with Cairo if I get those done

can you clarify if you're building with Apothecary or by hand?
Also do you have a copy of the libs you've successfully built so far? (something simple like a dropbox share might work). I'm elliotwoods (Seoul GMT+8) on Skype if you want to chat more directly

**Comment by elliotwoods** [comment] 2015-05-23 10:51
Assimp 3.0(?) [x64 VS2015 lib](https://drive.google.com/open?id=0B_S1z3_AWMRSfllGTUwycFk0WUQ4V3VIUVl6bUFvWU9pS1VBUXNsc3JaNzBTWTc5QXYydXc&authuser=0)

**Comment by elliotwoods** [comment] 2015-05-23 11:05
Build settings of OpenCV so far:

* No BUILD_DOCS
* No BUILD_TESTS
* No WITH_CUFFT, WITH_CUDA, WITH_CUBLAS (these are huge as far as I remember).

where are these kinds of settings customised in apothecary?

**Comment by ofTheo** [comment] 2015-05-23 12:18
-DGLFW_BUILD_UNIVERSAL=ON \
      -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 \
      -DCMAKE_OSX_ARCHITECTURES="x86_64" \
      -DENABLE_FAST_MATH=ON \
      -DCMAKE_CXX_FLAGS="-fvisibility-inlines-hidden -stdlib=libc++ -O3" \
      -DCMAKE_C_FLAGS="-fvisibility-inlines-hidden -stdlib=libc++ -O3" \
      -DCMAKE_BUILD_TYPE="Release" \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_DOCS=OFF \
      -DBUILD_EXAMPLES=OFF \
      -DBUILD_FAT_JAVA_LIB=OFF \
      -DBUILD_JASPER=OFF \
      -DBUILD_PACKAGE=OFF \
      -DBUILD_opencv_java=OFF \
      -DBUILD_opencv_python=OFF \
      -DBUILD_opencv_apps=OFF \
      -DBUILD_JPEG=OFF \
      -DBUILD_PNG=OFF \
      -DWITH_1394=OFF \
      -DWITH_CARBON=OFF \
      -DWITH_JPEG=OFF \
      -DWITH_PNG=OFF \
      -DWITH_FFMPEG=OFF \
      -DWITH_OPENCL=OFF \
      -DWITH_OPENCLAMDBLAS=OFF \
      -DWITH_OPENCLAMDFFT=OFF \
      -DWITH_GIGEAPI=OFF \
      -DWITH_CUDA=OFF \
      -DWITH_CUFFT=OFF \
      -DWITH_JASPER=OFF \
      -DWITH_LIBV4L=OFF \
      -DWITH_IMAGEIO=OFF \
      -DWITH_IPP=OFF \
      -DWITH_OPENNI=OFF \
      -DWITH_QT=OFF \
      -DWITH_QUICKTIME=OFF \
      -DWITH_V4L=OFF \
      -DWITH_PVAPI=OFF \
      -DBUILD_TESTS=OFF \
      -DBUILD_PERF_TESTS=OFF >> "${LOG}" 2>&1

**Comment by elliotwoods** [comment] 2015-05-23 14:06
http://pointclouds.org/news/2011/08/29/ffast-math/ suggests that ENABLE_FAST_MATH might be a bad idea. Also not sure what performance gains it gives (also if those optimisations are actually performance gains on modern systems / common applications). 

anyway will stick to these flags for the time being

**Comment by elliotwoods** [comment] 2015-05-23 14:10
i always thought it was a shame to build OpenCV without jpeg, png, ffmpeg, camera libs, etc
but anyway i'm using ofxCvMin which has all those anyway

sticking to the program and building..

**Comment by elliotwoods** [comment] 2015-05-23 14:16
# OpenCV

[OpenCV 2.4.9 x64 VS2015 (Release and Debug)](https://drive.google.com/open?id=0B_S1z3_AWMRSfi1Vc2pzZmZibDc1aGVQRVdEcjJsQlNoTG1WY21fX3NkMzBuWTNjX1pDb0E&authuser=0)

**Comment by ofTheo** [comment] 2015-05-23 19:24
awesome @elliotwoods want to just do it as a PR and merge it in?

**Comment by ofTheo** [comment] 2015-05-23 19:25
btw assimp should be the 3.0 version - I realized you asked this earlier.

**Comment by arturoc** [comment] 2015-05-24 08:33
we shoulnd't enable fast math on opencv. last time i tried it i think it completely broke face detection. fast math is really inacurate in terms of how float math is done

**Comment by DomAmato** [comment] 2015-05-24 20:45
Sorry has been a crazy week. I have been compiling using the apothecary scripts. I will compile all the libraries I have gotten through and host them. Is mediafire ok?

Cairo and OpenSSL are the only ones remaining and openSSL has a bit of an odd build sequence. I think Perl isn't making the .MAK files properly so when I run nmake it says that install isn't a recognized command.

I was using this as a reference: http://p-nand-q.com/programming/windows/building_openssl_with_visual_studio_2013.html

**Comment by danoli3** [comment] 2015-05-25 02:48
@arturoc I think this fast math issue may be a problem on iOS. Just tested face tracker after reading this... definitely need to recompile. (Script has fast-math for iOS).

**Comment by DomAmato** [comment] 2015-05-25 04:45
http://www.mediafire.com/download/f9sa4e9cfi99lnc

includes freeImage, freeType, glew, glfw, poco, rtaudio, tess2

also includes the updated scripts 

portAudio and fmodex dont have build steps so there wasn't anything to update for those

I also need to update libpng, pixman, zlib, and pkg-config for Cairo

**Comment by bakercp** [comment] 2015-05-25 04:54
Could you put this in a branch for testing rather than mediafire?

**Comment by DomAmato** [comment] 2015-05-25 17:48
https://github.com/DomAmato/openFrameworks/tree/VS2015Scripts

heres whats ive done so far

**Comment by LeoColomb** [comment] 2015-05-25 18:29
@DomAmato You rock! :smile: :clap: 

Some notes:
* POCO seems not to be build as `static_md` lib
* We need to update both win32 and x64 oF project to match new folders structures

**Comment by DomAmato** [comment] 2015-05-25 18:30
I noticed that too, I am patching the buildwin.cmd instead of using the cmake I will upload that as soon as I get it working

**Comment by DomAmato** [comment] 2015-05-25 20:52
OK I updated the poco script. Instead of using cmake it replaces the buildwin.cmd file with one I patched. The patch creates a copy of the vs120 projects, renames it to vs140, upgrades them, and then builds them. Win32 worked and I am in the middle of running the x64 but there hasnt been any issues thus far.

**Comment by DomAmato** [comment] 2015-05-26 06:06
OpenSSL should be good to go. It required a patch and I made a separate batch file though it could probably be handled in one shell script. Cairo is still being problematic. I've tried to follow this: http://www.cairographics.org/end_to_end_build_for_win32/ 

zlib is compilable via a cmake and so is libpng though there is also a vs project file that can be upgraded and compiled as well but not via command line. Not quite sure what is happening but trying: 

    vs-build libpng.vcproj "LIB Release"

results in an error

**Comment by liquidzym** [comment] 2015-05-28 03:07
been busy till next week,are we targeting the VS2015 both 32&64?

**Comment by DomAmato** [comment] 2015-05-28 18:01
I have been doing both. Apothecary has the ability to set the architecture to build for either so I don't see  why we couldn't account for both

**Comment by ofTheo** [comment] 2015-05-29 11:49
@DomAmato @elliotwoods  thanks for all this handwork on the libs. 

@DomAmato - could you do a PR for the branch you currently have. It will make it easier to see what is left to do. We can also merge in what you've done and then do a separate PR for Cairo. 

@elliotwoods could you do a PR for OpenCV and Assimp?

Thanks!!

**Comment by DomAmato** [comment] 2015-05-29 19:53
https://github.com/openframeworks/openFrameworks/pull/3876

**Comment by ofTheo** [comment] 2015-05-31 11:25
@DomAmato if getting Cairo building via script is tricky and holding things up feel free to build it manually and add the libs to #3876 

Thanks!!

**Comment by DomAmato** [comment] 2015-06-01 09:34
I will give it a push this week, I'm pretty confident it can be done easily enough just a matter of determining failure points and creating workarounds or patches

**Comment by DomAmato** [comment] 2015-06-02 18:54
Just a quick clarification we just need the libpng and zlib LIB files to build cairo but they don't come packaged with OF? There is a zlib DLL file in the export folder but is that related or can it be a separate build step? As for Pixman and Cairo itself I think I will just make a static lib project in VS that can live in the scripts and be moved over and compiled rather than using the make scripts (which don't work with nmake)

Based off of this but updated to support newer versions of cairo: https://sites.google.com/site/slinavlee/

**Comment by DomAmato** [comment] 2015-06-03 07:17
I got Cairo to compile with all the dependencies. Its a pretty convoluted process but I will try to clean it all up and post it tonight

**Comment by DomAmato** [comment] 2015-06-06 15:29
Everything should build now. I ran:

    apothecary update core

excluding the android script and everything compiled with both architectures. There is still probably a better option for Cairo but I made a project file that should build everything that the script downloads and builds. 

https://github.com/DomAmato/Cairo-VS

**Comment by ofTheo** [comment] 2015-06-06 23:59
Thanks so much @DomAmato! 
Looking forward for the PRs.

**Comment by DomAmato** [comment] 2015-06-07 00:01
forgot to post those haha

Scripts:
https://github.com/openframeworks/openFrameworks/pull/3894

Libraries:
https://github.com/openframeworks/openFrameworks/pull/3895

**Comment by DomAmato** [comment] 2015-06-07 08:49
New Scripts PR for updates made to the master: 
https://github.com/openframeworks/openFrameworks/pull/3897

**Comment by DomAmato** [comment] 2015-06-11 00:37
Im trying to build openframeworks with the compiled libraries and it works with vs2013 but with vs2015 I am getting an error that says 

    Error C2061 syntax error: identifier '_Dynamic_tag' (compiling source file ..\..\..\openFrameworks\app\ofAppGlutWindow.cpp)	openframeworksLib	C:\Users\Dominic\Desktop\openFrameworks\libs\openFrameworks\types\ofTypes.h	354

Immediately followed by:

    Error C2535 'ofPtr<T>::ofPtr(const ofPtr<Tp1> &)': member function already defined or declared (compiling source file ..\..\..\openFrameworks\app\ofAppGlutWindow.cpp)	openframeworksLib	C:\Users\Dominic\Desktop\openFrameworks\libs\openFrameworks\types\ofTypes.h	354

The code causing the error is:

    ofPtr(const ofPtr<Tp1>& __r, std::_Dynamic_tag)

which is found in ofTypes.h. I have a feeling this is related to poco but I am not sure.

**Comment by tgfrerer** [comment] 2015-06-11 13:40
@DomAmato how strange - this would hint that the compiler follows the pre-cpp11 path in ofTypes.h#L304. 

The line you name causing the error should be masked out by an `#ifdef` checking for cpp11 or above. The `#ifdef` sitting on line 304 in `ofTypes.h`.

Do you mind checking to what `__cpplusplus` resolves to in your environment? In VS2012 it used to be `199711L` - It should be `201103L` or above, so that ofPtr would be nothing else than a typedef'ed `shared_ptr`.

**Comment by arturoc** [comment] 2015-06-11 14:31
we can probably just remove all of the `ofPtr` code is super messy and most people using shared pointers are probably using github instead of the download which means that they are probably using shared_ptr instead since some time ago

**Comment by bakercp** [comment] 2015-06-11 14:34
I agree w/ removing it.  We've been talking about (and slowly deprecating it) for a while.  It's no longer used in the core and is a copy-paste replacement for `std::shared_ptr`... so +1 to streamlining.

**Comment by tgfrerer** [comment] 2015-06-11 14:35
+1 =)

**Comment by arturoc** [comment] 2015-06-11 17:31
ok, i've removed the old definitions but left the new one that works only for c++11 the problem with this one is that it can't be deprecated with an attribute so we might want to just remove it completely. in any case that should solve this problem i guess. it's weird though that the __cplusplus definition isn't returning the right value, perhaps in vs2015 you need to tell the compiler explicitly to use c++11 or later?

**Comment by tgfrerer** [comment] 2015-06-11 18:02
Hang on - I just had an afterghought - removing the old definition will most likely break OS X/ 32 bit, since it doesn't use cpp11 - unless we want to deprecate cpp98 altogether already =)

I think the issue is more related to that __cplusplus not being set as we'd expect by the VS tool chain. I found this issue in their bug tracker: 

https://connect.microsoft.com/VisualStudio/feedback/details/859110/visual-studio-2013-preprocessor-makro-cplusplus-shows-wrong-cplusplus-version

We might have to find a different cross-platform check for the available cpp version, if this is still happening in vs2015 - I could check tomorrow when I'm back near my windows machine. It could also affect other lines where we check for cpp11.

**Comment by LeoColomb** [comment] 2015-06-11 20:23
> if this is still happening in vs2015

No.

**Comment by DomAmato** [comment] 2015-06-11 20:24
I wonder if its a bug in the release candidate because its not a problem with the v120 toolset which is visual studio 2013's toolset. Microsoft's response is illuminating to why this might be a problem: 

> Most uses of the __cplusplus macro only check for its definition, and not its actual value. Due to the fuzziness of this compiler's conformance to any specific C++ standard, we recommend that you do not rely on the value of this macro in your code. 

To be fair I am on board with deprecating cpp98. OSX hasnt been 32 bit since what, snow leopard? my 2007 macbook pro which is barely clinging to life runs 10.10 and its free to upgrade though its

**Comment by arturoc** [comment] 2015-06-11 21:18
i think it's ok to have only the c++11 version as it'll only mean that ofPtr won't work on c++ < 2011 but other than that it'll compile...

i'd also vote for at least using libc++ for osx32 if not removing it completely. otherwise it's going to stop us from using c++11 in the core which brings a lot of really useful stuff

**Comment by liquidzym** [comment] 2015-06-12 02:25
something like this?
#if __cplusplus>=1900
#include <memory>
#else

i just did testing against last master,complied with both 32&64,although haven't testing with examples yet.

another line should be changing is in OfAppRunner.cpp
#if defined (TARGET_WIN32) || defined(TARGET_OSX)
	#include "ofQtUtils.h"
#endif
as 
#if defined (TARGET_OSX)
	#include "ofQtUtils.h"
#endif

since we're no longer to using quicktime under the Win,right?

**Comment by arturoc** [comment] 2015-06-12 08:29
this is a bug in visual studio, seems to be there since vs2012: https://connect.microsoft.com/VisualStudio/feedback/details/763051/a-value-of-predefined-macro-cplusplus-is-still-199711l  and no answer from ms.

i'm going to add a constant in ofConstants to check for CPP11 support that takes this into account

**Comment by DomAmato** [comment] 2015-06-12 08:30
I got everything to compile after the changes made to ofPtr and getting rid of the redefinition in ofConstants

    100:  #define _WIN32_WINNT 0x500

though doing so causes a problem in quicktime/processes.h 

    194: EXTERN_API( OSErr )
    GetProcessInformation  (const ProcessSerialNumber * PSN, ProcessInfoRec * info) THREEWORDINLINE(0x3F3C, 0x003A, 0xA88F);

which requires that to be commented out. Is @liquidzym correct in that windows isn't using quicktime? I had thought it was utilized for media playback but I have been utilizing the ofxWMFVideoPlayer addon

**Comment by arturoc** [comment] 2015-06-12 08:55
removing this from ofConstants:

```
	//this is for TryEnterCriticalSection
	//http://www.zeroc.com/forums/help-center/351-ice-1-2-tryentercriticalsection-problem.html
	/*#ifndef _WIN32_WINNT
		#define _WIN32_WINNT 0x501
	#endif
	#define WIN32_LEAN_AND_MEAN*/
```
and that include from ofAppRunner + a similar definition in ofExitCallback fixes those problems.

i'm getting a ton of errors from poco, again, with some definitions of network constants in ofAppURLFileLoader though. seems like poco somehow is including 2 different headers that define those constants, one as defines and the other as enum which makes the compiler freak out

**Comment by arturoc** [comment] 2015-06-12 08:57
also getting Severity	
```
Warning	C4003	not enough actual parameters for macro 'min' (compiling source file ..\..\..\openFrameworks\types\ofParameterGroup.cpp)	openframeworksLib	c:\users\arturo\code\openframeworks\libs\openframeworks\types\ofParameter.h	163
```
which should be solved by defining NOMINAX as we do in ofConstants but somehow it doesn`t

**Comment by arturoc** [comment] 2015-06-12 09:38
just managed to solve all the compiling problems but now i'm getting some linking issues. the libraries seem to be now in:

libs/libname/lib/vs/win32
libs/libname/lib/vs/x64

but the project properties files are still pointing to the old location at:

libs/libname/lib/vs

is this still missing or do i need to pull from somewhere else?

**Comment by DomAmato** [comment] 2015-06-12 09:42
I dont think it has been updated yet as I had to do it on my end as well. After I got all that done I am hitting some unresolved externals 

    Error LNK2001 unresolved external symbol _png_get_IHDR	projectGenerator  cairo-static.lib(cairo-png.obj)

I am looking at the cairo build see if I can resolve it since its looking for libpng's png.h

**Comment by arturoc** [comment] 2015-06-12 09:45
mmh, ok, there's some weird things:

- some libraries are still in their old location, i guess because there's only 32 bit versions? specifically glut and quicktime, i guess we can leave them as 32bit only but we would want to move them to vs/Win32

- fmod should be there for 64bit too

i'm going to send you a PR with my changes

**Comment by DomAmato** [comment] 2015-06-12 09:53
I got it to work, I needed to include the libpng.lib that was used to build cairo

**Comment by arturoc** [comment] 2015-06-12 09:57
yeah i'm seeing that too, libpng was missing, let me send you my changes first, there were several errors in the folder structure... then we can add libpng and merge it

**Comment by arturoc** [comment] 2015-06-12 10:08
i don't seem to be able to send a PR to your branch, can you commit only the libpng files?

**Comment by DomAmato** [comment] 2015-06-12 10:16
Its the same as the one included in the Cairo-VS libs folder which also happens to be built in the cairo apothecary formula. running:

    apothecary update libpng

should produce the lib file. Using the above method its located at build/libpng/projects/visualc71/win32_lib_release

**Comment by arturoc** [comment] 2015-06-12 10:26
ok great i'll do that. thanks!

**Comment by DomAmato** [comment] 2015-06-12 10:31
I have been successfully able to build the Win32 project generator in VC2015, x64 i get a litany of errors from quicktime. It all stems from the quicktime/ConditionalMacros.h since there is nothing to handle x64 architecture. with win32 it uses the _M_IX86 predefined macro, ill try adding the _M_AMD64 macro and see what happens

**Comment by arturoc** [comment] 2015-06-12 10:37
i have everything building now with cairo, in 64bit the only thing that seems to be missing is fmod, did you downloaded fmod or used the one that was already there?

**Comment by DomAmato** [comment] 2015-06-12 10:38
I used the one that was already there

**Comment by arturoc** [comment] 2015-06-12 10:39
perfect, so we need to find out which version it is and download the 64bit version if there's one available

**Comment by DomAmato** [comment] 2015-06-12 10:47
the .h file says FMOD_VERSION    0x00044221

**Comment by arturoc** [comment] 2015-06-12 13:51
so, 64bits still has some problems but i've just merged everything so we can at least have 32bits working and can keep working on everything else. i'm going to open a separate issue for 64bits. thanks so much for taking care of this!!

**Closed by arturoc** 2015-06-12 13:51 UTC
Labels: feature, visual studio

**Comment by bakercp** [comment] 2015-06-12 14:03
Yes, +1 for the epic work all.

**Comment by elliotwoods** [comment] 2015-06-24 07:31
so just to check. what's the status now?
we've got merged working VS2015 apothecary scripts for all libs?

and now just need to change up the rest of oF to use VS2015?
is there another issue for that?

**Comment by elliotwoods** [comment] 2015-06-24 07:32
and congrats all!

**Comment by elliotwoods** [comment] 2015-06-24 08:00
OK.

So 

### VS2015 / x64 WORKS with current mastser
Just update the Project Generator to use VS2015 rather than VS2012, also you need to setup the solution for x64)

### VS2015 / x86 DOESN'T WORK with current mastser
Lots of linker errors with Poco. I guess this is what you're discussing above

**Comment by DomAmato** [comment] 2015-06-24 17:14
The poco errors are actually related to the wrong architecture of openssl libs which are in my most recent PR
