### ISSUE TITLE
ofxOscSenderExample needs text polish

### ISSUE THREAD

**Issue by damian0815** [openframeworks/openFrameworks#3129] opened 2014-08-08 08:58 UTC
the text printed on screen is inaccurate and a bit misleading:

```
    buf = "sending osc messages to" + string(HOST) + ofToString(PORT);
    ofDrawBitmapString(buf, 10, 20);
    ofDrawBitmapString("move the mouse to send osc message [/mouse/position <x> <y>]", 10, 50);
    ofDrawBitmapString("click to send osc message [/mouse/button <button> <\"up\"|\"down\">]", 10, 65);
    ofDrawBitmapString("press A to send osc message [/test 1 3.5 hello <time>]", 10, 80);
```
- [ ] no spaces between host and port string
- [ ] `<button>` isn't sent on click

**Comment by tpltnt** [comment] 2015-07-26 11:29
I can reproduce the bug as of b5db2ccc97bbe7406ca5fa1feaff4f3cfdf2012b. I ran the ofxOscSenderExample and used [wireshark](https://www.wireshark.org/) to check. The filter to check for the mouse messages is `osc && udp.port eq 12345 && osc.message.string`. I do see a mouse button down message though.

**Comment by tpltnt** [comment] 2015-07-26 11:53
I tested with an external USB mouse. When i click left button, i get a "mouse down" for button 0. When i click with the right button, i get a "mouse down" for button 2. When i click with the scroll wheel, i get a "mouse down" for button 1. After clicking the scroll wheel, i only get "mouse up" messages, but no "mouse down" anymore. When i use the mouse(pad) on my computer, i can sort-of deterministically (but inconsistently) switching between "mouse up" and "mouse down" messages by clicking the middle button (button 1). I am seriously confused now.

**Comment by tpltnt** [comment] 2015-07-26 12:06
The host string issue is fixed now. The clicking issue confuses me. If anyone wants to pick up where i left off, check [my local branch](https://github.com/tpltnt/openFrameworks/tree/bugfix-issue3129).

**Comment by ShadowMitia** [comment] 2018-10-20 13:32
I tried to reproduce the bug but couldn't. Maybe this issue has been fixed since then? Or it was just a driver issue?

**Comment by arturoc** [comment] 2018-10-22 08:48
thanks!

**Closed** 2018-10-22 08:47 UTC
Labels: bitesize, bug, example, prelim-analysis
