### ISSUE TITLE
osx freetype libs won't link with < 10.10

### ISSUE THREAD

**Issue by tgfrerer** [openframeworks/openFrameworks#4284] opened 2015-08-22 12:32 UTC
4d32f4171b03b28bf3496809ab81c232374790af seems to have introduced static libs for OS X / freetype which won't link against deployment targets below 10.10.

Reverting to the previous commit, 1c9e03cdced50fb8aa4f5380bb712043b36e7022, solves the issue.

**Comment by bakercp** [comment] 2015-08-22 15:34
Hmm. Those libs were generated using the apothecary scripts so perhaps we
need to explicitly define a target? If you build the static libs on your
pre 10.10 machine does it link for you?

**Comment by tgfrerer** [comment] 2015-08-23 14:27
My machine is 10.11, unfortunately. But we're targeting 10.8 as the minimum platform on OS X, as far as I know. This possibly means that we'd have to re-build these libs on a 10.8 machine, or find a way in the apothecary script to set 10.8 as the build target for the library.

**Comment by ofTheo** [comment] 2015-08-24 16:12
From what I can remember you can set the SDK to build with via a CFLAG 

```
-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8
```
You can add older SDKs to your current Xcode app by copying the .sdk folder into /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/

**Comment by ofTheo** [comment] 2015-08-25 16:52
@tgfrerer I can't reproduce this. 
I'm on a 10.9 machine and have the 10.10 SDK / 10.9 and 10.8 SDKs installed. 

If I build against 10.8 or 10.10 sdk with current master the fontExample builds and runs without issue.

**Comment by ofTheo** [comment] 2015-08-28 15:13
I'm going to close this issue as I can't reproduce it. 
I've tried on a 10.10 machine and a 10.9 machine both targeting deployments of 10.7 or 10.8. 
I tried 32bit and 64bit and the font example ran fine with no issues. 

could you try again with latest master - I can reopen if there is still an issue. 

also could you post the linker errors - it could be helpful to see what they are?

**Comment by ofTheo** [comment] 2015-09-14 13:42
@arturoc pointed out that this is on 10.8 machines only.  Going to reopen as it seems that there is some issues with linking. ( @NickHardeman )

**Comment by bakercp** [comment] 2015-09-14 16:35
@ofTheo I've got 10.8 fired up and can make an attempt to recompile w/ xcode 5.*

**Comment by NickHardeman** [comment] 2015-09-15 14:35
I just tested this by compiling the font example on 10.8 and it worked as expected. :)

**Comment by bakercp** [comment] 2015-09-15 14:36
Thanks @NickHardeman

**Comment by bakercp** [comment] 2015-09-15 14:36
Closing this then.

**Closed by bakercp** 2015-09-15 14:36 UTC
Labels: critical, macOS
