### ISSUE TITLE
ofBuffer::getNextLine() errors out in Visual Studio

### ISSUE THREAD

**Issue by K0j0** [openframeworks/openFrameworks#3686] opened 2015-02-28 11:02 UTC
I'm using Visual Studio Express 2012 and the compiler that comes with it doesn't like ofBuffer::getNextLine(). The problem seems to be when ++currentLine is called and a new Line object is created.

```
ofBuffer::Line & ofBuffer::Line::operator++(){
	*this = Line(_current,_end);
	return *this;
}
```

The Line object is passed a begin and end iterator then does a comparison on them. That comparison eventually fails for me in the vector class with the error "vector iterators incompatible". 

It's pretty strange because I haven't had this issue on OSX or Linux (though Visual Studio is pretty finicky about a lot of stuff honestly). After Googling it a bit it looks like the VS compiler doesn't want to do a comparison on that end iterator.
http://stackoverflow.com/a/8471330/710249

This happens to me even in a brand new project. Has anyone else run into this? Are my compiler settings too strict or is this just the expected behavior of the VS compiler?

**Comment by bilderbuchi** [comment] 2015-03-02 19:45
pinging @openframeworks/windows

**Comment by chuckleplant** [comment] 2015-03-14 17:07
Can't reproduce with VS2012 premium and the latest OF changes. Not sure if premium vs express should have a different result on that.

**Comment by K0j0** [comment] 2015-04-07 18:56
Hm, that's interesting. I wonder what difference between express and premium would cause that? Just in case we were doing something different this is the code I was running
```
string path = "other.dat";
buff = ofBufferFromFile(path);
string line = buff.getNextLine(); // This line fails. The rest succeeds if you comment it out though
string data = buff.getText();
ofLog() << "Data from file: " << data;
```

So, I've been looking into this and it seems like the problem is in ofBufferFromFile(). I don't really understand what exactly is happening or why, but after stepping through the debugger several times it looks like the _begin, _current and _end iterators of ofBuffer::currentLine are wiped away when the buffer is returned from ofBufferFromFile(). This eventually causes a comparison operation between _begin and _end to fail when currentLine is incremented in getNextLine().

What's especially weird is a test I did in ofFileUtils.cpp
```
//--------------------------------------------------
ofBuffer ofBufferFromFile(const string & path, bool binary){
	ios_base::openmode mode = binary ? ifstream::binary : ios_base::in;
	ifstream istr(ofToDataPath(path, true).c_str(), mode);
	ofBuffer buffer(istr);
	istr.close();

	string foo = buffer.getNextLine(); // this works

	return buffer; // calling getNextLine() on the returned value fails
}
```

Again, this isn't happening on OSX or Linux. I debugged it in OSX and those iterators were unchanged after ofBufferFromFile() returns, but for some reason they're getting wiped in Windows. I wondered if the problem had to do with the function returning by value and the VS2012 compiler not liking that for some reason. However, the the string value of the Line is not wiped away just the iterators and I don't really know what to make of that.

Anyways, it appears that getNextLine() is deprecated anyway so I wonder if we should just let this go? It looks like the behaviour of getNextLine() and the other deprecated functions can be achieved with a Line iterator instead.

**Comment by bilderbuchi** [comment] 2015-06-17 13:29
ping @K0j0 @arturoc @openframeworks/windows what shall we do about this?

**Comment by tgfrerer** [comment] 2015-06-17 13:53
I just tested this on VS2015RC and could not reproduce the error (everything worked as it should). I think we can close this.

**Comment by bilderbuchi** [comment] 2015-06-17 14:02
thanks!

**Closed by bilderbuchi** 2015-06-17 14:02 UTC
Labels: bug, core, critical, visual studio
