### ISSUE TITLE
videoPlayerExample crashed in vs2017, but nothing in cosole window

### ISSUE THREAD

**Issue by szlidong998** [openframeworks/openFrameworks#6288] opened 2019-05-07 08:09 UTC
![image](https://user-images.githubusercontent.com/42959931/57283718-628f7780-70e2-11e9-9333-0625a1f8f152.png)
![image](https://user-images.githubusercontent.com/42959931/57283739-6cb17600-70e2-11e9-89dd-f25ff2f35122.png)

**Comment by szlidong998** [comment] 2019-05-07 09:15
here are some infomation, what driver shoud i setup, PC: WIN10, display: ATI radeon pro wx3100, driver: windows basicdisplays
[ error ] ofAppGLFWWindow: 65542: WGL: The driver does not appear to support OpenGL
[ error ] ofAppGLFWWindow: couldn't create GLFW window
[ error ] ofAppGLFWWindow: 65538: Cannot set swap interval without a current OpenGL or OpenGL ES context

**Comment by arturoc** [comment] 2019-05-07 09:33
this looks like you don't have an uptodate driver for your graphics card. going to close this since it looks like a problem on your end not a bug in OF. If you have any other questions please ask in the forum: https://forum.openframeworks.cc

**Closed by arturoc** 2019-05-07 09:33 UTC

**Comment by szlidong998** [comment] 2019-05-07 10:49
but win10 and other app works well, what's the solution?

**Comment by szlidong998** [comment] 2019-05-07 10:51
I update the display driver by radeon-software-adrenalin-2019-19.4.3-minimalsetup-190422_web.exe, result: nothing to be  upgrade.
