### ISSUE TITLE
Warning "Couldn't set UTF-8 locale, string manipulation functions won't work correctly"

### ISSUE THREAD

**Issue by mruegenberg** [openframeworks/openFrameworks#4100] opened 2015-07-20 09:19 UTC
I'm on Arch Linux and getting the above error message. It seems that the test introduced in 3a771d114f0da4dc62747b19c91aa710550af06b only works properly in Debian. There is, at the moment, no C.UTF-8 locale on Arch. (See also [here](http://comments.gmane.org/gmane.linux.arch.general/43880))

I think my string manipulation functions will probably be ok, since my default locale (which can be queried by `std::locale().name("")` (note the extra `""`)) is `en_US.utf-8`.

**Comment by bilderbuchi** [comment] 2015-07-20 09:27
ping @arturoc

**Comment by arturoc** [comment] 2015-07-20 10:37
yeah, thanks, i added that warning mostly to see if some people would have any problem with this. usually by default the locale is 'c' but if in platforms where there's no c.utf8 it defaults to the current system language it's totally ok. i'll remove the warning before the release. thanks

**Comment by procedural** [comment] 2015-07-20 12:34
Duplicate of https://github.com/openframeworks/openFrameworks/issues/4053 :)

**Comment by procedural** [comment] 2015-07-20 12:35
@mruegenberg hope you don't mind that I stole your title because it's clearer than what I had before :)

**Comment by bilderbuchi** [comment] 2015-07-20 12:56
thanks, closing as duplicate of #4053

**Closed by bilderbuchi** 2015-07-20 12:56 UTC
Labels: bug, core, section-internals
